### ISSUE TITLE
Error on STARTTLS?

### ISSUE THREAD

**Issue by davepage-mcr** [roundcube/roundcubemail-docker#102]
Hi there,

I have my Roundcube 1.4.8 docker container set up with `ROUNDCUBE_SMTP_SERVER=tls://remoteserver` and `ROUNDCUBE_SMTP_PORT=587`. When I try to send mail from Roundcube, I get the following error (seen with `$config['smtp_debug'] = True;`):

```
smtp: <d5afd62d> Connecting to tls://remoteserver:587...
smtp: <d5afd62d> Recv: 220 remoteserver ESMTP Exim 4.89 Sun, 13 Sep 2020 22:34:10 +0100
smtp: <d5afd62d> Send: EHLO webmail
smtp: <d5afd62d> Recv: 250-remoteserver Hello webmail [ip]
smtp: <d5afd62d> Recv: 250-SIZE 52428800
smtp: <d5afd62d> Recv: 250-8BITMIME
smtp: <d5afd62d> Recv: 250-PIPELINING
smtp: <d5afd62d> Recv: 250-STARTTLS
smtp: <d5afd62d> Recv: 250-PRDR
smtp: <d5afd62d> Recv: 250 HELP
smtp: <d5afd62d> Send: STARTTLS
smtp: <d5afd62d> Recv: 220 TLS go ahead
errors: <d5afd62d> PHP Error: STARTTLS failed (POST /?_task=mail&_unlock=loading1600032812908&_framed=1&_lang=en_US&_action=send)
smtp: <d5afd62d> Send: QUIT
```

On the server side, Exim reports:

```
2020-09-13 22:34:10 TLS error on connection from <server> (gnutls_handshake): A TLS fatal alert has been received.
```

To compare with: `swaks --from me --to me --server remoteserver:587 -tls` on the docker host:

```
=== Trying remoteserver:587...
=== Connected to remoteserver.
<-  220 remoteserver ESMTP Exim 4.89 Sun, 13 Sep 2020 23:00:36 +0100
 -> EHLO myserver
<-  250-remoteserver Hello myserver [ip]
<-  250-SIZE 52428800
<-  250-8BITMIME
<-  250-PIPELINING
<-  250-STARTTLS
<-  250-PRDR
<-  250 HELP
 -> STARTTLS
<-  220 TLS go ahead
=== TLS started with cipher TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256
=== TLS no local certificate set
=== TLS peer DN="/CN=remoteserver"
 ~> EHLO myserver
<~  250-remoteserver Hello myserver [ip]
[...]
```

... and continues delivery as normal. Is there anything I'm missing?

**Comment by thomascube** [comment]
> PHP Error: STARTTLS failed

Indicates that PHP cannot establish a secure connection (i.e. cannot upgrade the socket to an SSL connection). This is nothing we can fix in Roundcube (which runs in PHP). The reason for this could be:
* self-signed certificate of the smtp server
* smtp server uses a letsencrypt cert (see #72)
* tls version mismatch

You can try different options for the SMTP SSL connection by passing them as a [custom config](/roundcube/roundcubemail-docker#advanced-configuration) using the `smtp_conn_options` option. See the examples at [defaults.inc.php](/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L306).
