### ISSUE TITLE
Unable to set smtp_user and smtp_pass

### ISSUE THREAD

**Issue by tobgen** [roundcube/roundcubemail-docker#105]
I have some issues with sending email from roundcube using an internal smarthost.
After some digging it seems that it is not possible to set the values below. (Not supported by docker-entrypoint.sh)

$config['smtp_user'] = '';
$config['smtp_pass'] = '';

When I set them manually in config.inc.php and restart the container, it works like a charm.

**Comment by thomascube** [comment]
That's correct. We cannot provide ENV vars for all config options, there are just too many. See the [Advanced Configuration](https://github.com/roundcube/roundcubemail-docker#advanced-configuration) section in the README for the preferred way to add these options to your setup.
