### ISSUE TITLE
Have to change owner on every container start

### ISSUE THREAD

**Issue by igregma** [roundcube/roundcubemail-docker#115]
Hi there,

I'm running the container on my qnap nas...
On every start I get these errros...

`[Sat Nov 28 12:19:50.989213 2020] [php7:warn] [pid 103] [client 192.168.2.60:65026] PHP Warning:  Unknown: failed to open stream: Permission denied in Unknown o
n line 0, referer: http://192.168.2.2:32782/?_task=mail&_mbox=INBOX                                                                                             
[Sat Nov 28 12:19:50.989292 2020] [php7:error] [pid 103] [client 192.168.2.60:65026] PHP Fatal error:  Unknown: Failed opening required '/var/www/html/index.php
' (include_path='.:/usr/local/lib/php') in Unknown on line 0`

because also on every start the permissions are set (back) to 501:80 

![image](https://user-images.githubusercontent.com/6382524/100515468-c1ad5500-317c-11eb-9616-5897017b1663.png)

If I change it back to www-data:www-data or to 33:33 on the host, everything works again.

**Comment by thomascube** [comment]
Indeed, the owner and group are set to 501:80 but this never caused any problems so far as the files are readable for all.

**Comment by thomascube** [comment]
What "flavor" of Roundcube Docker image are you using? apache, fpm?

**Comment by igregma** [comment]
Apache...

Mabye it's something with the docker runtime of qnap, but had never problems before, also running many containers at "soho"

Just checked again, if I chmod everything to 501:80 I get an "access denied" for the htaccess file, if I keep everything untouched at start (like screensot above) it's an error 500.

**Comment by thomascube** [comment]
I have just pushed new builds with changed owner and group (root:root) to docker hub. Please pull and check if that works on your Qnap.

**Comment by igregma** [comment]
Now it's a total mess, can't get it running at all :-(

**Comment by igregma** [comment]
I think it was a problem with the QNAP itsefl... just recreated everything from scratch, deleted images, volumes... 
Copied the created temporary volumes to the permanent location and now everyhing smooth again :-)
Thanks!!
