### ISSUE TITLE
Letsencrypt support

### ISSUE THREAD

**Issue by netmindz** [roundcube/roundcubemail-docker#119]
Have you considered adding Letsencrypt support as everyone who is running this should really be behind https, so options would either be running nginx or similar as a proxy to this container or update this container to have https

**Comment by thomascube** [comment]
In a dockerized environment, the securing of connections to the outside world should be handled on a different level and in my opinion is not the responsibility of the application image. Please consider using the php-fpm variant in conjunction with an nginx container. You can find an example [here](https://github.com/roundcube/roundcubemail-docker/tree/master/examples#roundcube-served-from-php-fpm-via-nginx-using-a-postrgres-db).
