### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by rodolfovillaruz** [roundcube/roundcubemail-docker#12]
There's a problem with this line: https://github.com/roundcube/roundcubemail-docker/blob/8c21da90c65d41eea34a1e5d5e3e289961eed75d/php-apache/docker-entrypoint.sh#L77

It's not the right directory.

`ls: cannot access /var/roundcube/config/*.php: No such file or directory`

**Comment by thomascube** [comment]
`/var/roundcube/config` is defined as a VOLUME in Dockerfile. Make sure you have a valid mapping for it.

**Comment by rodolfovillaruz** [comment]
As far as I know, `/var/www/html/config` is the folder of configuration files, is there another batch of config files to store into `/var/roundcube/config`?

**Comment by rodolfovillaruz** [comment]
I see, that would be great.

**Comment by thomascube** [comment]
`ls /var/roundcube/config/*.php 2>/dev/null || true` should do the trick.

**Comment by madmath03** [comment]
@thomascube I think this has been fixed by #13. This issue should be closed.
