### ISSUE TITLE
Custom config path /var/roundcube/config/ missing in PHP include_path

### ISSUE THREAD

**Issue by marandus** [roundcube/roundcubemail-docker#128]
Docker tag: 1.4.x-apache

When trying to configure the managesieve plugin via a `managesieve.inc.php` file in `/var/roundcube/config/`, the PHP interpreter cannot include that file because it is missing in its `include_path` directive. Thus the plugin is not working (shows a failed to connect error when opening the filters options).

`
[Sun Apr 04 23:06:33.388446 2021] [php7:warn] [pid 58] [client 10.0.2.100:40992] PHP Warning:  include(/var/roundcube/config/managesieve.inc.php): failed to open stream: Permission denied in /var/www/html/config/config.docker.inc.php on line 12, referer: https://mail.example.tld/?_task=mail&_mbox=INBOX

[Sun Apr 04 23:06:33.388491 2021] [php7:warn] [pid 58] [client 10.0.2.100:40992] PHP Warning:  include(): Failed opening '/var/roundcube/config/managesieve.inc.php' for inclusion (include_path='/var/www/html/vendor/pear/pear_exception:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/net_ldap2:/var/www/html/vendor/pear/auth_sasl:/var/www/html/vendor/pear/console_commandline:/var/www/html/vendor/pear/crypt_gpg:/var/www/html/vendor/pear/mail_mime:/var/www/html/vendor/pear/net_idna2:/var/www/html/vendor/pear/net_socket:/var/www/html/vendor/pear/net_smtp:/var/www/html/program/lib:.:/usr/local/lib/php') in /var/www/html/config/config.docker.inc.php on line 12, referer: https://mail.example.tld/?_task=mail&_mbox=INBOX
`

**Comment by thomascube** [comment]
> the PHP interpreter cannot include that file because it is missing in its include_path directive.

That's not quite correct. If you look at the error message it says "Permission denied". Please check the filesystem permission setting of the folder you map into your docker container. This is nothing we can fix with our Docker image.
