### ISSUE TITLE
Missing .tx directory

### ISSUE THREAD

**Issue by sdondley** [roundcube/roundcubemail-docker#131]
In the root of the roundcube project, there is a .tx directory: https://github.com/roundcube/roundcubemail/tree/master/.tx

I don't see this directory in the docker container, however. I'm not sure if this is a problem or not but thought I'd bring it to your attention in case it is.

**Comment by thomascube** [comment]
The `.tx` directory holds settings to connect with the Transifex service which we use for translation work. This is solely used for development and also isn't included in the distribution packages. This is nothing you'd need in a Docker container either.
