### ISSUE TITLE
Missing unzip tool

### ISSUE THREAD

**Issue by cbhp** [roundcube/roundcubemail-docker#134]
I'm getting these log lines

> Installing dependencies from lock file
> Package operations: 0 installs, 4 updates, 0 removals
> As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
> This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
> Installing 'unzip' may remediate them.

So should 'unzip' be added to the Dockerfile?

**Comment by pabzm** [comment]
`unzip` is present these days.
