### ISSUE TITLE
Need help to install plugins

### ISSUE THREAD

**Issue by UbioZur** [roundcube/roundcubemail-docker#135]
Hi,
Sorry I am new to that docker thing, and to roundcube also, I haven't found the information to be able to install plugin on roundcube (that are not part of the image), so third party plugins.
kind of related to https://github.com/roundcube/roundcubemail-docker/pull/104 and https://github.com/roundcube/roundcubemail-docker/issues/97

Mostly I am looking at trying ident_switch and twofactor_gauthenticator.

I guess I have to mount a volume to the host (but which one?) install the plugin and setup the $config in my config.inc.php

Any help/direction would be appreciated. I am hoping it wouldn't require to build the docker image to try the plugins (https://github.com/roundcube/roundcubemail-docker#building-a-docker-image)

**Comment by thomascube** [comment]
Please see this: https://github.com/roundcube/roundcubemail-docker/tree/master/examples#installing-roundcube-plugins

**Comment by UbioZur** [comment]
Thanks, maybe this section could/should be added to the main folder readme.
