### ISSUE TITLE
Example request: Serve roundcubemail-docker with non-docker-nginx

### ISSUE THREAD

**Issue by omgMath** [roundcube/roundcubemail-docker#136]
Hi all.

This is more a question/example request than an issue.
I'd like to do the the following setup:
- :heavy_check_mark: MySql served via Docker
- :heavy_check_mark: Roundcube (fpm-alpine) served via Docker - connecting to above database
- :x: Plain (i.e. non-docker) Nginx, serving the Roundcube app

I'm not very experienced with neither PHP nor Docker nor Nginx (which is probably why I haven't figured out it on my own).

Therefore I'd like to ask for another example on this case, since I'm assuming this should possible.

Thanks for any support!

**Comment by loelkes** [comment]
The nginx-container connects over port 9000 to the php-fpm. You would have to open port 9000 (e.g. `docker run -v 127.0.0.1:9000:9000 ...`) on the PHP container and then tell your nginx to connect to localhost:9000 (e.g. `fastcgi_pass localhost:9000;`).

I would recommend to look up some resources on Docker, nginx and PHP-FPM and close this issue.

**Comment by thomascube** [comment]
For the non-docker nginx server you can use the config template for [our example](https://github.com/roundcube/roundcubemail-docker/blob/master/examples/nginx/templates/default.conf.template) and replace `NGINX_PHP_CGI` with `<your-docker-host>:9000` once you opened port 9000 as @loelkes suggested.
