### ISSUE TITLE
Add more security

### ISSUE THREAD

**Issue by williamdes** [roundcube/roundcubemail-docker#139]
IMO this was a good bad move: https://github.com/roundcube/roundcubemail-docker/commit/cc3a6dbf6e5a389ddb4c59f1ac920a747b250549

In a security point of view you could force your key and it would work, making the GPG check useless
It would be nice to check the imported GPG KEY ID

**Comment by thomascube** [comment]
I know, it was kind of a desperate change because I couldn't find any working public keyservers. I'm certainly open for suggestions, adding an ID check could be a start.

**Comment by williamdes** [comment]
I will do that when I start my multi arch task: soon I hope

**Comment by thomascube** [comment]
ID check has been added.

**Comment by williamdes** [comment]
> ID check has been added.

In https://github.com/roundcube/roundcubemail-docker/commit/b85710be9ca5f6e0807811123243b554ca90842e
