### ISSUE TITLE
Do not declare volumes in Dockerfile?

### ISSUE THREAD

**Issue by loelkes** [roundcube/roundcubemail-docker#142]
I'm building my own Images where I install plugins and their requirements, directly copy config files etc. Unfortunately the volumes are declared in the initial Dockerfile. I would prefer that users can declare, if they need it, persistent volumes in the docker command oder docker-compose file. I can't "undeclare" them and each time I build a new container, I have to delete the volumes as well in the deployment to apply my changes or create a custom entrypoint script an overwrite the config files.

I would prefer not declaring the volumes. If this is not an option I'll stick with the entrypoint solution. Please let me know what you think.

**Comment by thomascube** [comment]
I see your point but entirely removing the volumes would make the average "setup" a bit more complicated and requires more documentation and understanding for certain scenarios (e.g. custom plugin installation). Therefore it's not a easy decision to change this. I guess we could get rid of `VOLUME /var/roundcube/db` and `VOLUME /tmp/roundcube-temp` but the other two are actually required to survive container restarts without loosing data.

**Comment by loelkes** [comment]
Data is preserved at container restarts, it'y only lost if you remove the container. 

IMHO: 
* I understand what you say but at no point from your manual I see the need for persistent volumes? Additional configurations are directly mounted and custom plugins are added by building a custom image.
* Most Docker manuals and HowTos go the other way around: persistence (even if containers are removed) for config or data must be explicitly configured, either by volumes or by mounts.

I believe, from a "big picture" point of view, that leaving the volumes declaration in the initial Dockerfile, which can't be revoked later, makes it less flexible and more complex to work with than expecting people who want data persistence to declare their volume, mount etc. in a single line of code, which is also common throughout the docker universe.

I don't want to fight, I just want to share my thought and hopefully improve the project :).

**Comment by thomascube** [comment]
@loelkes many thanks for sharing your thoughts and I didn't close this ticket because I think you have a valid point here. I'll try a few scenarios without these volume declarations in order to see whether we can actually get rid of them as you suggest.

**Comment by thomascube** [comment]
We just updated the `latest-*` [tags](https://hub.docker.com/r/roundcube/roundcubemail/tags) with new images that no longer contain volume definitions. Please report if you find any problems.

**Comment by allentc** [comment]
Writing to thank you for this change.  I've been forced to use docker-copyedit to purge unwanted volumes from base images, including roundcube-docker.  Persistence is much better served by documenting volume mount points for the image user.
