### ISSUE TITLE
Please add an env var to disable SSL certificate check

### ISSUE THREAD

**Issue by jsalatiel** [roundcube/roundcubemail-docker#146]
Would it be possible to add some environment variable to disable SSL certificate verification for the imap over tls/ssl ?

**Comment by thomascube** [comment]
You can overwrite any config option you'd like by providing a custom config file to your container. See the [Advanced configuration](/roundcube/roundcubemail-docker#advanced-configuration) section. The option in question is [`imap_conn_options`](https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L157).

Please understand that we don't map all possible options to Docker container variables.
