### ISSUE TITLE
Environment variable for default language?

### ISSUE THREAD

**Issue by CarloMartini** [roundcube/roundcubemail-docker#147]
Hello,
How can I set the default language for all users? Shouldn't there be an environment variable for that, too?

I have already tried to add a /var/roundcube/config/additional_config.php with the code:

```
<?php
$config['language'] = 'it_IT'

```
But that seems to work only for the login page, not the inner interface.

Thank you

**Comment by thomascube** [comment]
Adding a custom config file like you did is actually the way to go. Not sure why this doesn't work entirely but introducing an env var wouldn't solve the issue. I'll try to investigate this soon...

**Comment by pabzm** [comment]
Closing as stale
