### ISSUE TITLE
not able to add plugin via composer 

### ISSUE THREAD

**Issue by maja68** [roundcube/roundcubemail-docker#15]
Hi,

i tried to install `roundcube/carddav` into rc installation by composer.

I copied the `composer.json-dist` to `composer.json`.

The I added the  `roundcube/carddav` into `composer.json` :

```
{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net/"
        },
        {
            "type": "vcs",
            "url": "https://git.kolab.org/diffusion/PNL/php-net_ldap.git"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "pear/pear-core-minimal": "~1.10.1",
        "pear/net_socket": "~1.2.1",
        "pear/auth_sasl": "~1.1.0",
        "pear/net_idna2": "~0.2.0",
        "pear/mail_mime": "~1.10.0",
        "pear/net_smtp": "~1.7.1",
        "pear/crypt_gpg": "~1.6.0",
        "pear/net_sieve": "~1.4.0",
        "roundcube/plugin-installer": "~0.1.6",
        "endroid/qr-code": "~1.6.5",
        "roundcube/carddav": "~3.0.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8.36 || ^5.7.15"
    },
    "suggest": {
        "pear/net_ldap2": "~2.2.0 required for connecting to LDAP",
        "kolab/Net_LDAP3": "dev-master required for connecting to LDAP"
    }
}
```
when I run `php composer.phar install` I get the following error:

```
Loading composer repositories with package information                                             
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - endroid/qr-code 1.6.6 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - endroid/qr-code 1.6.5 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - endroid/qr-code 1.6.6 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for endroid/qr-code ~1.6.5 -> satisfiable by endroid/qr-code[1.6.5, 1.6.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

May be the missing required php extension could be included by default into the container?

Cheers

**Comment by maja68** [comment]
To overcome the issue of the missing php extension I removed the `endroid\qr-code` component.

Then I got an error regarding the php version

```
Loading composer repositories with package information                                             
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - roundcube/carddav 3.0.1 requires php >=5.6.18 -> your PHP version (5.6.11) does not satisfy that requirement.
    - roundcube/carddav 3.0.1 requires php >=5.6.18 -> your PHP version (5.6.11) does not satisfy that requirement.
    - Installation request for roundcube/carddav ~3.0.1 -> satisfiable by roundcube/carddav[3.0.1].
```

Is there a reason to stick with php 5.6.11?

**Comment by thomascube** [comment]
Is this really related to the Docker version of Roundcube? The Docker image comes with the GD extension and all core-modules pre-installed.

Please note that `roundcube/carddav` is a 3rd party plugin we do not know nor maintain. Please report problems the plugin authors.

**Comment by maja68** [comment]
Hi,

thank you for your comment. Sure its a version requirement from `roundcube/carddav`. I just want to highlight there is a plugin require a higher php version and it might be possible to update to a more current version of php.

I made a comment on this on `roundcube/carddav` but so far no response.

> The Docker image comes with the GD extension and all core-modules pre-installed.

What does "GD" mean?

Is there a core-module allowing to connect an addressbook  to a CardDav server?

**Comment by thomascube** [comment]
Basically plugin authors are free to add additional requirements and as long as they are specified in the plugin's composer.json file, you'll get the according notice. There's nothing wrong on our side neither can we fix anything here.

The GD extension is used render images and is required by the `endroid/qr-code` library as your initial report shows. It's also listed as a requirement for Roundcube in the [INSTALL](https://github.com/roundcube/roundcubemail/blob/master/INSTALL) instructions and you should meet these requirements.

Anyway, this all is not related to the Docker version of Roundcube as it's based on PHP7.1 with all requirements included. Closing this issue as irrelevant.
