### ISSUE TITLE
Update to Roundcube 1.5.0

### ISSUE THREAD

**Issue by foorschtbar** [roundcube/roundcubemail-docker#152]
Hello, RC 1.5.0 is available since October 18, 2021. When will the Docker image be updated?

https://roundcube.net/news/2021/10/18/roundcube-1.5.0-released

**Comment by joachimneu** [comment]
There was a mention in #148 that 1.5.0 images are currently held back to investigate reports of failing MySQL schema upgrades.

**Comment by NotANormalNerd** [comment]
Hey, Version 1.5.1 was just released.
Just wanted to say, that I am waiting on this release for the multiple SMTP server feature and would really like to get rid of my old installation.
If you need help, let me know.

Best regards,
Dennis
