### ISSUE TITLE
Always "connection reset" without any clear clue

### ISSUE THREAD

**Issue by romu70** [roundcube/roundcubemail-docker#156]
Hi.
I'm trying to setup a Roundcube container on my nas. And I can't figure out why it doesn't work.

Here is the command which creates the container:

```
docker run -d --name roundcube-1.4 -e ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.gandi.net -e ROUNDCUBEMAIL_DEFAULT_PORT=993 -e ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.gandi.net -e ROUNDCUBEMAIL_SMTP_PORT=587 -e ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=10M -e ROUNDCUBEMAIL_DB_TYPE=pgsql -e ROUNDCUBEMAIL_DB_HOST=__my_nas_IP__ -e ROUNDCUBEMAIL_DB_PORT=__my_PG_port__ -e ROUNDCUBEMAIL_DB_USER=__my_roundcube_user__ -e ROUNDCUBEMAIL_DB_PASSWORD=__my_roundcube_pwd__ -e ROUNDCUBEMAIL_DB_NAME=roundcube -v roundcube:/var/roundcube/config/ -p 4800:80 roundcube/roundcubemail:1.4.x-fpm-alpine
```
The container starts and stays active, here is the log:
```
roundcubemail not found in /var/www/html - copying now...
Complete! ROUNDCUBEMAIL has been successfully copied to /var/www/html
wait-for-it.sh: waiting 30 seconds for IP:PORT
wait-for-it.sh: IP:PORT is available after 1 seconds
Write root config to /var/www/html/config/config.inc.php
Write Docker config to /var/www/html/config/config.docker.inc.php
Creating database schema... [OK]
[11-Nov-2021 11:14:41] NOTICE: fpm is running, pid 1
[11-Nov-2021 11:14:41] NOTICE: ready to handle connections
```
I can see my Postgres DB is correctly initiated and populated. So everything seems ok, but when I try to connect to http://__my_nas_IP__:4800, I always get "Connection reset".

My nas runs a bunch of containers which host some web applications, all setup in a similar way, without any problem.
Any idea?

**Comment by thomascube** [comment]
You apparently chose the *fpm-alpine* version. Please note that PHP-FPM is not actually a web server but a CGI processor. Therefore you cannot connect to this service from a web browser and the container does not expose port 80 but 9000. When using the FPM version of Roundcube you need to connect it with a webserver like nginx or apache (see the [examples](https://github.com/roundcube/roundcubemail-docker/tree/master/examples)) or you better choose the apache version of the Roundcube image. This includes a webserver and will expose port 80 as you expected it.

**Comment by romu70** [comment]
Thanks a lot Thomas.
