### ISSUE TITLE
Coordinate release of roundcubemail-docker and roundcubemail

### ISSUE THREAD

**Issue by ckristo** [roundcube/roundcubemail-docker#157]
I just saw that new versions of roundcubemail with Security fixes (1.4.12 and 1.3.17) were published, but there are no updated Docker images on Docker Hub available yet. Especially for new releases incl. Security fixes, it would be great if Docker images would be build and pushed to Docker Hub in a coordinated fashion with the release. It would be cool if this would be automatized  (for minor updates at least - I saw the issues with the 1.5 update causing some troubles).

**Comment by ckristo** [comment]
Seems there is already an issue related to that which was closed, #8

**Comment by thomascube** [comment]
Yes, we're working on this. Unfortunately Docker Hub has disabled the auto-build feature for free plans and we're currently looking for an alternative way to build and deploy new releases. Thanks for your patience.

**Comment by floryn90** [comment]
why not trying to use github action to build and push image to docker hub?

**Comment by thomascube** [comment]
Yes, that's what we're trying to do...

**Comment by williamdes** [comment]
Done in #201 ?

**Comment by pabzm** [comment]
As far as I can tell this is solved
