### ISSUE TITLE
Newly built docker containers fail to connect to LDAP

### ISSUE THREAD

**Issue by thinkl33t** [roundcube/roundcubemail-docker#160]
We have two containers, one with roundcube 1.4.11 from a couple of weeks ago, which works fine, and the updated version with roundcube 1.4.12 from yesterday which doesn't.

Our roundcube system is tied to our LDAPS server, which uses a letsencrypt-provided TLS certificate.

On the new version, we were receiving the error message: "user not found in the address book".

To debug this, I have connected into the containers and manually installed ldaputils and gnutls-bin from apt.

- On both, `gnutls-cli ldap.example.org:636` works fine
- On both, `openssl s_client -connect ldap.example.org:636` works fine
- On the old container, an ldapsearch works fine
- On the new container, the same ldapsearch fails to connect:

```
# ldapsearch -v -d 8 -b "dc=example,dc=org" -D "uid=srv_webmail,cn=sysaccounts,cn=etc,dc=example,dc=org" -Wx -H ldaps://ldap.example.org '(uid=srv_webmail)'
ldap_initialize( ldaps://ldap.example.org:636/??base )
Enter LDAP Password: 
TLS: can't connect: (unknown error code).
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
```

After a bit of poking around, i had a hypothesis that the lack of /etc/ldap/ldap.conf was causing ldapsearch to not be able to authenticate, and tried installing `libldap-common`.  This fixes the issue.

**Comment by thinkl33t** [comment]
We have also encountered this error with the nextcloud container we use: https://github.com/nextcloud/docker/pull/1586 - they use the same php container upstreams as you do, maybe this is a change that should be made in the php containers?

**Comment by thinkl33t** [comment]
I've opened https://github.com/docker-library/php/issues/1228 upstream to see what the php container developers say, though for now it would probably be useful for us to install this within the roundcube dockerfiles.

**Comment by thomascube** [comment]
@thinkl33t Thanks for tracking this down. Let's see what how upstream issue is being handled and otherwise we'll install `libldap-common` in our containers.

**Comment by thinkl33t** [comment]
Upstream directed me to an unrelated program then closed the issue, so i think we can probably assume they aren't going to be massively helpful :upside_down_face:

**Comment by thomascube** [comment]
@thinkl33t I just pushed new tags `1.5.x-apache` and `latest-apache` with the change listed above. However, I'm not sure this actually fixes the issue as I just added `libldap-common` to the build dependencies which are reverted again. Could you please test because we're lacking a setup with an LDAP service to test against. If the problem persists, please re-open this issue.
