### ISSUE TITLE
missing composer.phar?

### ISSUE THREAD

**Issue by MatthiasLohr** [roundcube/roundcubemail-docker#163]
Hi,

in https://github.com/roundcube/roundcubemail-docker/blob/master/apache/docker-entrypoint.sh#L21, when Roundcube is considered to do an update, `composer.phar update --no-dev` is called. However, `composer.phar` is not contained in the Docker image. Am I missing something here or should that be fixed?

Best regards
Matthias

**Comment by thomascube** [comment]
Indeed, `composer.phar` is not available anymore. The Dockerfile changed recently to copy composer from the `composer:2` image.
