### ISSUE TITLE
Daily error - mpm_prefork:error - server reached MaxRequestWorkers setting

### ISSUE THREAD

**Issue by nunnsby** [roundcube/roundcubemail-docker#164]
Very weird behaviour, as it appears to happen daily at around 1200 or 1300. Not on the hour, as that would point to some cronjob "maybe", but definitely always within the first 20 minutes of either 1200 or 1300. Mostly I notice 1203 or 1303 in my logs, but not always that timing. This example below is from 1213.

Full Error:
Jan 04 12:13:34 server 2e02499ff03e [660]: [Tue Jan 04 12:13:34.080180 2022] [mpm_prefork:error] [pid 1] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting

Configuration:
Docker - image: roundcube/roundcubemail:latest
sqlite DB

I am running a Proxy in front of this container, and am polling this container every 5 mins from an external location for a 200 response for uptime tracking. 

Whilst the general sentiment on the net appears to be to tweak the MaxRequest Workers setting, for a container that is actually only used once a day, even less, to check mails, it feels unlikely that the webserver config needs to be tweaked. Also, this only started happening about 2 months back. Before then, it was 100% and never had any issues. What changed? nothing that I did.

There are no cronjobs on the host.

Only way to resolve is to restart the container.

Any thoughts or logs I could provide to assist figuring out the issue here?

**Comment by thomascube** [comment]
Strange issue indeed. What changed? Maybe the base PHP/Apache image we're using had changes. We do not track these.
The only idea I have about the situation you describe is that connections to the apache (from the periodic uptime check via the proxy) do not close the connection and thus the apache worker process that is started for each http request remains active. Try to investigate on that by connecting to your Roundcube container and use netstat. You might need to install it first with `apt-get install net-tools`. Here are a few useful commands to watch tcp connections and apache processes:

```
# get number of apache processes
ps aux | grep apache | wc -l
# watch active tcp connections
watch netstat -ant
```

**Comment by thomascube** [comment]
@nunnsby Have you been able to investigate the issue on your running containers. There's nothing else we could provide.
