### ISSUE TITLE
$config['imap_host'] not set in nightly container, breaks login

### ISSUE THREAD

**Issue by guysoft** [roundcube/roundcubemail-docker#165]
Hey,
I built of current master $config['imap_host'] not set in [nightly container](https://github.com/roundcube/roundcubemail-docker/tree/master/nightly)

But login does not work unless I add in ``/var/www/html/config/config.docker.inc.php``

```php
$config['imap_host'] = 'tls://example.com:143';
```

Otherwise server tries to connect on localhost.
``$config['default_host']`` Is set but does not seem to be taken in to account

Using: https://github.com/roundcube/roundcubemail-docker/blob/master/examples/docker-compose-simple.yaml

**Comment by thomascube** [comment]
The same changes apply to smtp_server. See https://github.com/roundcube/roundcubemail/blob/master/CHANGELOG.md

**Comment by guysoft** [comment]
@thomascube cool, so does my PR make sense?  Should I change anything?

**Comment by thomascube** [comment]
Yes it makes total sense, I just forgot about breaking changes in git master and the nightly profile here. However, the changes need to be extended. We can pick up your suggestions and thus you don't need to update your PR. I'll just close it and apply the changes directly.
