### ISSUE TITLE
Embedding plugins in the image

### ISSUE THREAD

**Issue by Kitanit** [roundcube/roundcubemail-docker#169]
Hello, can you help make an example of how the dockerfile will look when using for example this plugin (https://github.com/mfreiholz/persistent_login)

**Comment by thomascube** [comment]
An example is provided in the README file of this repository: https://github.com/roundcube/roundcubemail-docker#building-a-docker-image.

In order to activate the installed plugins, list them with the ROUNDCUBEMAIL_PLUGINS env variable:
```
-e ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,persistent_login
```

**Comment by Kitanit** [comment]
> An example is provided in the README file of this repository: https://github.com/roundcube/roundcubemail-docker#building-a-docker-image.
> 
> In order to activate the installed plugins, list them with the ROUNDCUBEMAIL_PLUGINS env variable:
> 
> ```
> -e ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,persistent_login
> ```

Yes, but what does "installed" mean, which folder to put the plugin or it will find it somehow?

**Comment by thomascube** [comment]
The composer command installs the given plugin into the folder inside the Docker image where all the Roundcube code is stored: `/usr/src/roundcubemail/`. With that, the plugin is "available" in this Docker image and can be activated using the `ROUNDCUBEMAIL_PLUGINS` env variable.

**Comment by Kitanit** [comment]
@thomascube 
> The composer command installs the given plugin into the folder inside the Docker image where all the Roundcube code is stored: `/usr/src/roundcubemail/`. With that, the plugin is "available" in this Docker image and can be activated using the `ROUNDCUBEMAIL_PLUGINS` env variable.

I mean, is it enough to add wget here for example to download the plugin into the folder?
![image](https://user-images.githubusercontent.com/65107731/151300087-081b13f9-e409-4409-86a0-4ff21e728055.png)

**Comment by thomascube** [comment]
@Kitanit If you can't install the plugin via composer, then download (an unpack) it into `/usr/src/roundcubemail/plugins/<plugin-name>/`. That's enough to have it available to be activated via the `ROUNDCUBEMAIL_PLUGINS` env variable.

**Comment by Kitanit** [comment]
> @Kitanit If you can't install the plugin via composer, then download (an unpack) it into `/usr/src/roundcubemail/plugins/<plugin-name>/`. That's enough to have it available to be activated via the `ROUNDCUBEMAIL_PLUGINS` env variable.

@thomascube do I need to create this folder?
*I already have the docker version running
![image](https://user-images.githubusercontent.com/65107731/152733121-117a8f63-9fb6-42f4-b141-e7e0425d55d8.png)
