### ISSUE TITLE
Missing Docker Images for Roundcube Webmail 1.4.13

### ISSUE THREAD

**Issue by raoulbhatia** [roundcube/roundcubemail-docker#171]
Dear maintainers,

Docker hub is missing images for Roundcube Webmail 1.4.13 [1], see
* https://hub.docker.com/r/roundcube/roundcubemail/tags?page=1&name=1.4.13 vs.
* https://hub.docker.com/r/roundcube/roundcubemail/tags?page=1&name=1.4.12

It would be great to see the image to be provided officially.

Thanks,
Raoul
[1] https://github.com/roundcube/roundcubemail/releases/tag/1.4.13

**Comment by thomascube** [comment]
Thanks for the hint, new builds have now been published.
