### ISSUE TITLE
Document whether replication is supported

### ISSUE THREAD

**Issue by haslersn** [roundcube/roundcubemail-docker#176]
Hi! I'd like to know if it's supported to run multiple replicas of the roundcube container (given that they access the same database). My primary intention is high availability, but load-balancing would be a side-effect, too. however, I didn't find anything about this in the documentation.

If this is possible in principle, are there any directories that must be shared between the replicas? Does the configured `temp_dir` need to be a shared directory, or can every replica have its own `temp_dir`? I think this depends on whether specific files in the `temp_dir` are only used in a single php invocation or across multiple php invocations.

**Comment by pabzm** [comment]
Closing as stale

**Comment by haslersn** [comment]
Was closing this an automatic action? I think this is still not solved, i.e., documentation is missing.

In my organization we run roundcube with multiple replicas with `temp_dir` on a shared filesystem (CephFS).

**Comment by pabzm** [comment]
No, I closed it because it hadn't had activity for over 2 years, which often means that no one has got a thorough interest.

But as you are showing active interest I'm happy to re-open it.

Would you maybe write a short paragraph for the README (or a standalone document) on this topic?

**Comment by thomascube** [comment]
Roundcube can be configured HA. The basics are documented [here](https://github.com/roundcube/roundcubemail/wiki/Configuration:-Load-balanced-Setup).
