### ISSUE TITLE
Roundcube Webmail 1.6-rc on docker hub

### ISSUE THREAD

**Issue by navossoc** [roundcube/roundcubemail-docker#179]
Hi, I would like to test this version but it isn't available yet on docker hub.

When will this release be pushed to docker hub?

[]'s

**Comment by thomascube** [comment]
Roundcube 1.6-rc is not yet released but this repo contains a template for [nightly builds](/roundcube/roundcubemail-docker/tree/master/nightly) which pull the latest Git master version. You can build it on your own.
