### ISSUE TITLE
serve under subpath

### ISSUE THREAD

**Issue by deraljoscha** [roundcube/roundcubemail-docker#180]
So I have this roundcube docker image up and running under mydomain.com:9000
I'm using apache2 as reverse proxy and I have other apps configured as well.

now I want to serve rouncube under mydomain.com/mail
I have my apache2 config properly, but is there a variable to add so roundcube is served under a subpath?
Right now the login fails and isn't properly displayed, I can only reach rc under mydomain.com:9000

thanks in advance

**Comment by ghnp5** [comment]
Same. Log-in is redirecting to `/?_task=login` instead of `/subpath/?_task=login`.
This was working before.

**Comment by logopk** [comment]
Old behavior was `./?_task=login`

**Comment by bubeck** [comment]
Seems to be a duplicate of https://github.com/roundcube/roundcubemail-docker/issues/186
