### ISSUE TITLE
Sieve now seems to require tls:// prefix on hostname

### ISSUE THREAD

**Issue by chongma** [roundcube/roundcubemail-docker#192]
Sieve wouldn't connect and had `php error: this server doesn't support any authentication methods.` 
When debugging the "SASL" was empty ""

usetls was set
`$config['managesieve_usetls'] = true;`

Appending tls:// to the domain fixed it
`$config['managesieve_host'] = 'tls://domain.tld';`

It also wasn't respecting the managesieve.inc.php that was copied into the config.  I had to edit directly in plugins/managesieve/config.inc/php which means the config will be overwritten

Would be nice to have a good readme on managesieve

**Comment by maiksd** [comment]
I just fixed my setup adding the 'tls://' prefix as you mentioned, but using 1.6.2 it worked putting that into the external config file.

**Comment by pabzm** [comment]
This appears to be solved, thus closing.
