### ISSUE TITLE
SMTP authentication error

### ISSUE THREAD

**Issue by nixe-** [roundcube/roundcubemail-docker#196]
If an unauthenticated SMTP server is used to send e-mail, then Roundcube 1.6 (Docker) gives an error _SMTP Error ($code): Authentication failed._

This is happening because in defaults.inc.php config there's defined smtp_user as '%u' and smtp_pass as '%p'. There's no possibility to set these in Docker Env, so Roundcube tries to authenticate even it's unauthenticated server. To bypass this problem at the moment, you have to manually add smtp_user and smtp_pass as empty value to config.inc.php. But these should definitely be configurable in Docker Env

**Comment by thomascube** [comment]
Yes, we don't have env vars defined for all possible config options. The smtp_user/pass might be a sane addition indeed. For now you can override them with additional config files as described in the [advanced configuration](/roundcube/roundcubemail-docker#advanced-configuration) section in the README.

**Comment by nixe-** [comment]
> Yes, we don't have env vars defined for all possible config options. The smtp_user/pass might be a sane addition indeed. For now you can override them with additional config files as described in the [advanced configuration](/roundcube/roundcubemail-docker#advanced-configuration) section in the README.

How did I miss that, this is definitely a good solution.
