### ISSUE TITLE
/var/ww/html is empty

### ISSUE THREAD

**Issue by tinsaeDev** [roundcube/roundcubemail-docker#197]
The /var/ww/html  directory is not being populated, I have tried to clean install but still the directory is empty.

My configuration files is 

FROM roundcube/roundcubemail:1.6-beta-fpm-alpine

COPY docker/roundcube-fpm/conf.d/* /var/roundcube/config/

COPY docker/roundcube-fpm/entrypoint.sh "/docker-entrypoint/entrypoint.sh"
RUN chmod +x "/docker-entrypoint/entrypoint.sh"

ENTRYPOINT [ "/docker-entrypoint/entrypoint.sh" ]

**Comment by thomascube** [comment]
I'm sorry but I fail to understand what you're trying to achieve with this Dockerfile.
The /var/www/html directory is populated by the `docker-entrypoint.sh` script of the Roundcube Docker images. Check the container logs to find out what's going wrong.

**Comment by tinsaeDev** [comment]
I  need to run some scripts  at startup alongside  the default script.

**Comment by williamdes** [comment]
Can you share once more the full context please?

**Comment by pabzm** [comment]
Closing as stale
