### ISSUE TITLE
docker-compose example installation not working

### ISSUE THREAD

**Issue by pilere** [roundcube/roundcubemail-docker#202]
Hi all,

I am using this configuration : 
https://github.com/roundcube/roundcubemail-docker/blob/master/examples/docker-compose-fpm.yaml

but I got this error in the roundcubemail container : 
```
roundcubemail      | Running update script at target...
roundcubemail      | WARNING: Mimetype to file extension mapping doesn't work properly!
roundcubemail      | Please check the 'mime_types' config option and run this script again.
roundcubemail      | Executing database schema update.
```

EDIT : for the next problem, I got it solved by adding : 
`include       mime.types;`

~~and when I try the login page, I have broken style with no error within the developper tab (nothing else than 200) and nothing in the logs of any container .... if I try to load a svg image with a direct link / url I got the data, but no images ...

where should I look for errors of better nginx conf ? : 
~~
```
worker_processes auto;

events {}
http {
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    server {
        listen 80;
        server_name mail.mydomain.com;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        } 
        location / {
            return 301 https://$host$request_uri;
        } 
    }
    server {
        listen 443 ssl;

        server_name mail.mydomain.com;
        index index.php index.html;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /var/www/html;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass roundcubemail:9000; #${NGINX_PHP_CGI};
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        ssl_certificate /etc/letsencrypt/live/mail.mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mail.mydomain.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    }
}
```

**Comment by IronWillDevops** [comment]
Hello, I also have difficulties with installing according to this instruction, I think that the error is in the absence of this module, but I did not understand how to solve it
![image](https://user-images.githubusercontent.com/78508681/211125911-11c1b23d-42d5-4b3a-85b6-470408f7f608.png)
If you manage to solve the problem, I will be grateful if you share the solution

**Comment by pilere** [comment]
I did manage it to work, check my edit.
