### ISSUE TITLE
Roundcube Apache Container logs not going to stdout and stderr

### ISSUE THREAD

**Issue by montgomery-auber** [roundcube/roundcubemail-docker#205]
The logs for apache in the Apache container go to a log dir inside the container instead of going to docker logs. For a couple of years I have been re-building with Dockerfile. I know that it's the same in the 1.6 that we have been working on.
```
FROM roundcube/roundcubemail:1.4.11-apache
RUN ln -sf /dev/stdout /var/log/apache2/access.log \
	&& ln -sf /dev/stderr /var/log/apache2/error.log
```

**Comment by thomascube** [comment]
I cannot confirm this. At least with the latest build (roundcube/roundcubemail:1.6.0-apache) I can see all access logs in the container console.
