### ISSUE TITLE
Can't add attachments over 3 MB

### ISSUE THREAD

**Issue by michalkulik** [roundcube/roundcubemail-docker#210]
After delploying docker-compose container with roundcube in compose window I can't add attachment over 3 MB.
Getting 500 server error in logs:
192.168.69.135 - - [16/Mar/2023:10:18:12 +0000] "POST /?_task=mail&_remote=1&_from=compose&_id=3785288356412eaa92f87f&_uploadid=upload1678961893358&_action=upload HTTP/1.1" 500 545 "http://192.168.69.110:9002/?_task=mail&_action=compose&_id=3785288356412eaa92f87f" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"

I have ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE variable set to 50M. Any ideas?

**Comment by raoulbhatia** [comment]
Hi.

I am running roundcube on Linux and unfortunately cannot comment on Windows.

I've set the following
1. **roundcube**: `ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=102400000` in my docker environment
2. **roundcube**: I mount a custom `php.ini` that I mount into docker: `/etc/php/xxx/php.ini:/usr/local/etc/php/conf.d/zzz_roundcube-custom.ini`
3. **php**: `upload_max_filesize = 5G` and `upload_max_filesize = 5G` in said custom `php.ini`
4. **nginx**: `proxy_max_temp_file_size 10240m` in my nginx config, which acts as a proxy and is handling TLS.

All of that is not fully consistent, but it works in my setup.

**Comment by pabzm** [comment]
Closing as stale
