### ISSUE TITLE
What is the default user and password?

### ISSUE THREAD

**Issue by iszhi** [roundcube/roundcubemail-docker#218]
Today, I tried the docker version with the following commander "docker run -e ROUNDCUBEMAIL_DEFAULT_HOST=mail -e ROUNDCUBEMAIL_SMTP_SERVER=mail -p 8000:80 -d roundcube/roundcubemail"

HOwever, what is the default user and password?
![image](https://github.com/roundcube/roundcubemail-docker/assets/33443222/137e66cb-2b0c-4520-9c5d-b46cd219f1e9)

**Comment by krupikivan** [comment]
Did you figure it out?
