### ISSUE TITLE
Publish 1.6.1

### ISSUE THREAD

**Issue by maiksd** [roundcube/roundcubemail-docker#219]
Release 1.6.1 of roundcubemail has been out since January, and there still is no docker image update of it. 1.6.1 fixes many bugs. Please publish the update as docker image.

**Comment by maiksd** [comment]
Ok, make that 1.6.2...

**Comment by jtackaberry** [comment]
I do wish the docker image would be considered part of the main project release cycle.

**Comment by williamdes** [comment]
Should this one be closed, since 1.6.2 is out ?
