### ISSUE TITLE
Container image release for 1.6.2?

### ISSUE THREAD

**Issue by spantaleev** [roundcube/roundcubemail-docker#222]
Looks like a container image fro roundcubemail 1.6.2 hasn't been published to [roundcubeorg/roundcubemail](https://hub.docker.com/r/roundcubeorg/roundcubemail) on Docker Hub yet.

Are you doing this manually and it's been forgotten? Can we expect an image to be released?

**Comment by thomascube** [comment]
Version 1.6.2 is building right now...

Also, [roundcube/roundcubemail](https://hub.docker.com/r/roundcube/roundcubemail) has been and still is the one and only official repo.

**Comment by williamdes** [comment]
Please close this issue, it's out
