### ISSUE TITLE
Roundcube 1.6.2: Unable to load dynamic libraries

### ISSUE THREAD

**Issue by binsentsu** [roundcube/roundcubemail-docker#224]
Hi,

After installing docker roundcube 1.6.2 I had issues regarding php libraries gd, imagick and zip which could not be loaded. The issue seems to be related to the fact that the php:8.1-apache image is now based on debian 12 bookworm iso bullseye. After some investigation it seems others had same issue. Rebuilding the image with ldd changes from this [PR](https://github.com/docker-library/wordpress/pull/834) fixes the issue.

`roundcubemail    | PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/gd.so (libpng16.so.16: cannot open shared
 object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/gd.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/gd.so.so: cannot open shar
ed object file: No such file or directory)) in Unknown on line 0
roundcubemail    | PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick (/usr/local/lib/php/extensions/
no-debug-non-zts-20210902/imagick: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so (libMagickWand-6.Q16.so.6: c
annot open shared object file: No such file or directory)) in Unknown on line 0
roundcubemail    | PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/zip.so (libzip.so.4: cannot open shared 
object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/zip.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/zip.so.so: cannot open sha
red object file: No such file or directory)) in Unknown on line 0`

**Comment by zeyadtamimi** [comment]
I am seeing the same issue as well

**Comment by williamdes** [comment]
Same issue as https://github.com/phpmyadmin/docker/issues/416

**Comment by williamdes** [comment]
@thomascube this is extremely important, I am sorry to have to ping you
Could you please review and merge https://github.com/roundcube/roundcubemail-docker/pull/226 🙏🏻 ?

This exact change was accepted in docker official repository for the phpMyAdmin image: https://github.com/docker-library/official-images/pull/14960
