### ISSUE TITLE
Security update 1.6.3

### ISSUE THREAD

**Issue by maiksd** [roundcube/roundcubemail-docker#228]
Hi, the security update 1.6.3 has appeared three days ago. Ideally, the docker image should be updated with it at the same time, but at least it should come shortly after.

**Comment by navossoc** [comment]
@maiksd It's available.

**Comment by maiksd** [comment]
Cool, thanks. Updating worked, even though I don't see the tag yet.

**Comment by navossoc** [comment]
I saw it here:
https://hub.docker.com/r/roundcube/roundcubemail/tags?page=1&name=1.6.3
