### ISSUE TITLE
Image tag no longer matches Roundcube version

### ISSUE THREAD

**Issue by ThinkChaos** [roundcube/roundcubemail-docker#229]
Since #221 was merged, the version in `.github/workflows/build.yml` needs to be made dynamic instead of hardcoded.  
Current situation led to having the `1.6.2-*` images actually being v1.6.3.

**Comment by thomascube** [comment]
Grmpf... I knew we missed something...

**Comment by thomascube** [comment]
Updating the workflow as well in update.sh (see b74e6d277)

**Comment by ThinkChaos** [comment]
Seems like making the workflow update itself needs an extra permission: https://github.com/roundcube/roundcubemail-docker/actions/runs/6490022510/job/17625204164

**Comment by thomascube** [comment]
Should now be fixed with 3d875bdb69c8409236
