### ISSUE TITLE
cannot configure managesieve host

### ISSUE THREAD

**Issue by mmerickel** [roundcube/roundcubemail-docker#233]
Similar to #79, I am having trouble defining config for the `managesieve_host`.

### Config

Using image `roundcube/roundcubemail:1.6.5-apache`.

#### env vars

```
ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail
ROUNDCUBEMAIL_DEFAULT_PORT=993
ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail
ROUNDCUBEMAIL_SMTP_PORT=465

ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=50M

ROUNDCUBEMAIL_DB_TYPE=sqlite

# head /dev/urandom | base64 | head -c 24
ROUNDCUBEMAIL_DES_KEY=REDACTED

ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,managesieve
```

#### /var/roundcube/config/local.inc.php

```php
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
```

#### /var/roundcube/config/managesieve.inc.php

```php
$config['managesieve_host'] = 'tls://mail:4190';
```

### Logs

These access logs show the manageseive using localhost:4190.

```
front-roundcube-1  | errors: <03981fe5> PHP Error: Connection refused (GET /?_task=settings&_action=plugin.managesieve)
front-roundcube-1  | errors: <03981fe5> PHP Error: Unable to connect to managesieve on localhost:4190 in /var/www/html/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 227 (GET /?_task=settings&_action=plugin.managesieve)
front-roundcube-1  | errors: <03981fe5> PHP Error: Not currently in AUTHORISATION state (GET /?_task=settings&_action=plugin.managesieve)
front-roundcube-1  | errors: <03981fe5> PHP Error: Not currently connected (GET /?_task=settings&_action=plugin.managesieve)
```

### Discussion

I can confirm that /var/www/html/config/config.docker.inc.php is including the local and managesieve files. SMTP and IMAP are working fine, which requires the config in `local.inc.php`. However, no matter what I do the managesieve still uses localhost.

**Comment by mmerickel** [comment]
If I modify the actual plugin source to use my host instead of localhost then it does connect to my sieve server correctly. I think the issue is just around how the config is loaded into the plugin in this container. I've also tried putting it in `/var/www/html/plugins/managesieve/config.inc.php` to no effect.

**Comment by mmerickel** [comment]
Any suggestions here? Thanks!

**Comment by mmerickel** [comment]
bumping this again, thanks for any ideas - I'm unclear where else to go to for roundcube support, especially with the docker image :-)

**Comment by mmerickel** [comment]
more bumping..

**Comment by osiloke** [comment]
You need to wrap your php code with PHP tags

**/var/roundcube/config/managesieve.inc.php**
```
<?php
$config['managesieve_host'] = 'tls://mail:4190';
?>
```

**Comment by Elkropac** [comment]
> more bumping..

Hi, i don't know, if it's the correct way, but i use volume to directly map config.inc.php from outside to plugins, like this in `docker-compose`:
```
    volumes:
      - ./data/www:/var/www/html
      - ./data/plugins/managesieve/config.inc.php:/var/www/html/plugins/managesieve/config.inc.php:ro
      - ./data/plugins/password/config.inc.php:/var/www/html/plugins/password/config.inc.php:ro
```
