### ISSUE TITLE
Roundcube Migration to Docker - Connection Issue with Full Email Address

### ISSUE THREAD

**Issue by EmileSpa** [roundcube/roundcubemail-docker#234]
Hello all,

I am currently in the process of migrating Roundcube from a traditional host to a Docker environment. While I've successfully restored the database within the Docker setup, I'm encountering an issue with the configuration when using the full email address for login.

Here's a snippet of my configuration in customconfig.inc.php:

```
$config['username_domain'] = 'domain.nl';
$config['imap_host'] = 'ssl://mail.domain.nl:993';
$config['smtp_host'] = 'tls://mail.domain.nl:587';
```

And in config.docker.inc.php (auto-generated):

```
  $config['imap_host'] = 'ssl://mail.domain.nl:993';
  $config['smtp_host'] = 'tls://mail.domain.nl:587';
```

The problem arises when attempting to log in using the full email address (e.g., name@domain.nl). It results in a timeout, and I noticed that Roundcube is trying to connect to hostname.domain.nl:143. Strangely, this hostname and port are not configured anywhere in my settings, and port 143 is closed on the host.

When logging in with just the username (without the domain part), everything works fine, and Roundcube establishes a connection to ssl://mail.domain.nl:993.

I want to ensure that Roundcube consistently connects to ssl://mail.domain.nl:993, regardless of whether only the name or the full email address is used for login. Can anyone shed light on where Roundcube might be picking up the hostname.domain.nl:143 configuration when using the full email address for login?

Any assistance or insights into resolving this issue would be greatly appreciated.

Thank you in advance!

**Comment by EmileSpa** [comment]
It turns out that the issue was caused by a specific Roundcube plugin. Upon deactivating this plugin, the login process started working seamlessly, and Roundcube consistently connected to ssl://mail.domain.nl:993, regardless of whether the full email address or just the username was used.

**Comment by Murazaki** [comment]
> It turns out that the issue was caused by a specific Roundcube plugin. Upon deactivating this plugin, the login process started working seamlessly, and Roundcube consistently connected to ssl://mail.domain.nl:993, regardless of whether the full email address or just the username was used.

@EmileSpa For the record, which plugin was it ?
