### ISSUE TITLE
How do I remove the plugin correctly?

### ISSUE THREAD

**Issue by VlaK0r** [roundcube/roundcubemail-docker#236]
Hello!
Thank you for your work!

Please tell me how to remove the plugin?
I installed it with the following command 
 `docker exec -it roundcubemail composer require johndoh/contextmenu --update-no-dev`

**Comment by williamdes** [comment]
Please check the new env `ROUNDCUBEMAIL_PLUGINS` with `ROUNDCUBEMAIL_INSTALL_PLUGINS=1`

**Comment by pabzm** [comment]
Closing as stale.
