### ISSUE TITLE
Using `ROUNDCUBEMAIL_REQUEST_PATH` doesn't work in Apache2

### ISSUE THREAD

**Issue by aureq** [roundcube/roundcubemail-docker#239]
Hi,

I've set `ROUNDCUBEMAIL_REQUEST_PATH` to `/webmail` while using the apache2 based image. Unfortunately, apache2 was complaining the URL didn't exist (404).

Upon inspection (https://github.com/roundcube/roundcubemail-docker/pull/208 and https://github.com/roundcube/roundcubemail-docker/commit/913cd6f41774e69168511288e089f9592805d390), I found that the default apache configuration is missing an `Alias` to match with the value stored in `ROUNDCUBEMAIL_REQUEST_PATH`.

```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # missing Alias
        Alias /webmail /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

Adding this line allows me to run the container on kubernetes (at least I have the login page).

**Comment by thomascube** [comment]
The Roundcube application in the Docker container is meant to run at root (/). The ROUNDCUBEMAIL_REQUEST_PATH option was added to handle cases where http requests go through a revers-proxy before hitting the container where the original path information isn't available. Your solution with an Alias certainly works but I don't consider this a bug in the Roundcube docker image.
