### ISSUE TITLE
Disabling access logs

### ISSUE THREAD

**Issue by krokyze** [roundcube/roundcubemail-docker#242]
Are there any configuration options to disable these access logs? I'm using `roundcube/roundcubemail:1.6.6-apache`

`10.241.0.15 - - [22/Mar/2024:01:25:28 +0200] "GET /skins/elastic/images/logo.svg HTTP/1.1" 200 680 "https://****/skins/elastic/watermark.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"`

**Comment by jasoncodes** [comment]
I ended up creating a custom script to disable Apache’s logging which then I mounted as `/start.sh` and set as the container’s `command` in my `docker-compose.yml`:

```sh
#!/bin/bash
set -euo pipefail

ln -sf /dev/null /var/log/apache2/access.log
ln -sf /dev/null /var/log/apache2/other_vhosts_access.log

exec apache2-foreground
```

**Comment by krokyze** [comment]
> I ended up creating a custom script to disable Apache’s logging which then I mounted as `/start.sh` and set as the container’s `command` in my `docker-compose.yml`:
> 
> ```shell
> #!/bin/bash
> set -euo pipefail
> 
> ln -sf /dev/null /var/log/apache2/access.log
> ln -sf /dev/null /var/log/apache2/other_vhosts_access.log
> 
> exec apache2-foreground
> ```

Thanks for the info, I managed to disable it like this:

```
  roundcubemail:
    build:
      context: .
      dockerfile_inline: |
        FROM roundcube/roundcubemail:1.6.6-apache
        RUN ln -sf /dev/null /var/log/apache2/access.log && \
            ln -sf /dev/null /var/log/apache2/other_vhosts_access.log
    container_name: roundcubemail
```
