### ISSUE TITLE
Unable to get to the dashboard after a successful login

### ISSUE THREAD

**Issue by goldmont** [roundcube/roundcubemail-docker#253]
Hi,

After a successful login (response code 200 OK), Roundcube simply refresh the login page preventing me from getting to the dashboard. The URL is then updated to the following: `https://mail.mydomain.it/?_task=login`.

What is `?_task=login`?

My mail server is an instance of `docker-mailserver` with SSL enabled using Let's Encrypt certificates. Everything works good with other clients like `Mozilla Thunderbird`.

However, below you can see what Roundcube receives from the reverse proxy (Traefik in this case):
```
Hostname: 9c95f04624a4
IP: 127.0.0.1
IP: ::1
IP: 172.18.0.4
IP: 172.19.0.4
RemoteAddr: 172.18.0.2:46672
GET / HTTP/1.1
Host: mail.mydomain.it
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7,zh-CN;q=0.6,zh;q=0.5
Cookie: roundcube_sessid=412cc99f536a1bb251bc49f7520fd33f
Dnt: 1
Priority: u=0, i
Purpose: prefetch
Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-Purpose: prefetch;prerender
Upgrade-Insecure-Requests: 1
X-Forwarded-For: <ip_address>
X-Forwarded-Host: mail.mydomain.it
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: d340cf36b7b4
X-Real-Ip: <ip_address>
```

Here is my Roundcube environment:
```
ROUNDCUBEMAIL_DEFAULT_HOST: ssl://mail.mydomain.it
ROUNDCUBEMAIL_DEFAULT_PORT: 993
ROUNDCUBEMAIL_SMTP_SERVER: ssl://mail.mydomain.it
ROUNDCUBEMAIL_SMTP_PORT: 465
ROUNDCUBEMAIL_REQUEST_PATH: /
ROUNDCUBEMAIL_ASPELL_DICTS: en,it
ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 10MB
ROUNDCUBEMAIL_SKIN: elastic
ROUNDCUBEMAIL_DB_TYPE: mysql
ROUNDCUBEMAIL_DB_HOST: <db_host>
ROUNDCUBEMAIL_DB_PORT: <db_port>
ROUNDCUBEMAIL_DB_USER: <db_user>
ROUNDCUBEMAIL_DB_PASSWORD: <password>
ROUNDCUBEMAIL_DB_NAME: <db_name>
```

MySQL setup is working good.

After a few hours of research, I'm still unable to understand what's the real problem with Roundcube but I saw that many are having the same issue. What am I missing? Thank you in advance.

**Comment by goldmont** [comment]
Of course I'm running the latest version available.

**Comment by goldmont** [comment]
Anybody?

**Comment by pabzm** [comment]
HTTP status 200 does not mean that the login was successful, and being redirected back to the login page (`task=login`) indicated the contrary: that the login did not succeed. You probably have an issue with authentication, maybe the logs can help you with debugging.

**Comment by goldmont** [comment]
> HTTP status 200 does not mean that the login was successful, and being redirected back to the login page (`task=login`) indicated the contrary: that the login did not succeed. You probably have an issue with authentication, maybe the logs can help you with debugging.

Hi,

This is what I see in my logs:

```
172.18.0.2 - - [13/Jun/2024:09:31:08 +0000] "GET / HTTP/1.1" 200 2755 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
[Thu Jun 13 09:31:13.060291 2024] [php:warn] [pid 134] [client 172.18.0.2:52970] PHP Warning:  Unknown: POST Content-Length of 188 bytes exceeds the limit of 10 bytes in Unknown on line 0, referer: https://mail.mydomain.it/
172.18.0.2 - - [13/Jun/2024:09:31:13 +0000] "POST /?_task=login HTTP/1.1" 200 2758 "https://mail.mydomain.it/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
```

No errors are logged. Only a warning. Any suggestion?

**Comment by pabzm** [comment]
Maybe setting some log-options will tell more, see https://github.com/roundcube/roundcubemail/blob/d8b2c3b659f2607b9e9b7052e4854b94656a9d4e/config/defaults.inc.php

But this is not a support forum, we can't provide operational support for your setup. Unless you have a reason to think there's a bug in Roundcube, please look for help e.g. in the forum: https://www.roundcubeforum.net/

**Comment by thomascube** [comment]
Looks like a configuration problem (broken session storage or cookie settings). Not a docker issue.
