### ISSUE TITLE
enigma plugin not supported by container

### ISSUE THREAD

**Issue by sasilen** [roundcube/roundcubemail-docker#255]
Container is missing gpg binary

`PHP Error: Enigma plugin: GPG binary not found. If you are sure the GPG binary is installed, please specify the location of the GPG binary using the 'binary' driver option. in /var/www/html/plugins/enigma/lib/enigma_engine.php on line 91`

with alpine, this can be easily fixed by installing needed binary 
`"apk add gpg"`

also there could be default directory defined or environment option for providing enigma_pgp_homedir
eg:  $config['enigma_pgp_homedir'] = RCUBE_INSTALL_PATH . '/pgp';

**Comment by pabzm** [comment]
Thank you for the hint! The plugins included in the shipped code should indeed work.

**Comment by pabzm** [comment]
@sasilen This should be fixed in the images as of next week. Thanks again for reporting!
