### ISSUE TITLE
Include testrunner image in this repo

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail-docker#257]
I built a docker-compose based setup to locally run the tests for roundcubemail using a custom docker image. To reduce execution times of the test runs I'd like to use service-containers in the CI workflows, too. For that we'd need downloadable images with several PHP versions.

@alecpl [suggested](https://github.com/roundcube/roundcubemail/pull/9525#issuecomment-2196887469) to store the scripts and build the images in this repository.

Would you agree to set that up here if I post a PR?

**Comment by alecpl** [comment]
> @alecpl [suggested](https://github.com/roundcube/roundcubemail/pull/9525#issuecomment-2196887469) to store the scripts and build the images in this repository.

Actually, I just said I don't want any docker files in the roundcubemail repo root.

**Comment by pabzm** [comment]
I didn't mean to misquote you, sorry for the misunderstanding.

Your position is not quite clear to me: do you prefer the `Dockerfile`s and related scripts (including the workflows to build the images) in the main repo or in this one? (For me both variants are fine.)

**Comment by alecpl** [comment]
> Your position is not quite clear to me: do you prefer the `Dockerfile`s and related scripts (including the workflows to build the images) in the main repo or in this one? (For me both variants are fine.)

Sorry if I wasn't clear. I don't really care about docker, but I know if we put Dockerfile in Roundcube root folder, it will be confusing considering that roundcubemail-docker exists. If you can make it working with `.ci/Dockerfile` I'm fine with that.

**Comment by pabzm** [comment]
Thank you for the explanation, so I'll continue in the main repo! 👍
