### ISSUE TITLE
When will 1.6.8 be on dockerhub?

### ISSUE THREAD

**Issue by AuspeXeu** [roundcube/roundcubemail-docker#259]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

When will 1.6.8 be on dockerhub?

### What version of Roundcube are you using?

1.6.8

**Comment by raoulbhatia** [comment]
Hopefully #258 will get merged soon

**Comment by thomascube** [comment]
We have a [Github action](https://github.com/roundcube/roundcubemail-docker/blob/master/.github/workflows/update-sh.yml) which runs every night checking for a new version. Just give it a few more hours to run before opening issues or submitting pull requests ;-)

**Comment by cbhp** [comment]
@thomascube what about 1.5.8 as LTS for docker, please?
