### ISSUE TITLE
Publish nightly

### ISSUE THREAD

**Issue by dschmidt** [roundcube/roundcubemail-docker#261]
There's a nightly folder in this project and it apparently can be used to build a docker image from roundcube's master branch - but afaict it's not pushed anywhere.

I want to test changes in master that are not part of 1.6.8 right now and it would be superconvenient if I could just use a prebuilt docker image for that.

**Comment by thomascube** [comment]
The nightly folder got a bit forgotten and certainly needs a make-over. The idea of having nightly builds pushed to a docker registry sounds good. Not sure yet if we should use the same image and repo name as the official releases (roundcube/roundcubemail) or better use some more distinct naming.

**Comment by dschmidt** [comment]
I'm fine with a specific tag or a separate image name. 

Fwiw I've sent a PR to fix building the nightly image. It might not be in a super great shape, but it works for me so far.

**Comment by dschmidt** [comment]
Thanks! It does of course!
