### ISSUE TITLE
managesieve redirect has no access to sendmail

### ISSUE THREAD

**Issue by chiefbrain** [roundcube/roundcubemail-docker#264]
On using a redirect rule in managesieve
```
if header :contains "subject" ["order", "buy"] {
  redirect "orders@company.dom";
}
```
the following error occurs:
`redirect action: failed to redirect message to <redirect@domain.tld>: Failed to execute sendmail (temporary failure)`

Apparently, sendmail from the hosts system is needed.

**Comment by waja** [comment]
> the following error occurs:
> redirect action: failed to redirect message to <redirect@domain.tld>: Failed to execute sendmail (temporary failure)

This is issued by the IMAP server (dovecot) and not related to the roundcube instance.

**Comment by chiefbrain** [comment]
> This is issued by the IMAP server (dovecot) and not related to the roundcube instance.

I thought the directory containing the log is mounted to the container so that roundcube can write to it and since sendmail in the container is used, it produces the error. But the log directory is not mounted.
I suppose roundcube communicates with the managesieve daemon so this error originates from the hosts as you said. Thank you for your quick reply.
