### ISSUE TITLE
Invalid request No data was saved

### ISSUE THREAD

**Issue by EnergeticMrMask** [roundcube/roundcubemail-docker#278]
Hello.
I am trying to implement an email service using `docker-mailserver` and `roundcubemail` through Docker in one server.
Everything was going smoothly until I tried to log into the email using `roundcubemail`.
I entered the correct username and password, but it prompted me with `Invalid request! No data was saved.`
 I didn't find any relevant solutions about this online. I found a related discussion in Roundcube's issues, but I think the solution provided doesn't seem suitable for Docker.
The docker-mailserver seems to be running fine; the problem should be with Roundcube Mail. I believe there is an issue with my configuration, but I don't know where the problem lies.
This is my docker run command, which I modified based on the docker run instructions and compose file from the examples and the README.
```
docker run \
  --name roundcubemail \
  --network host \  #I also tried use "-p 80:80" here, but there is no different
  -v /etc/docker/roundcubemail/config/data:/var/www/html \
  -v /etc/docker/roundcubemail/config/db/sqlite:/var/roundcube/db \
  -e ROUNDCUBEMAIL_DEFAULT_HOST=localhost \ #I also tried use "192.168.x.x" which is the server's IP and "mail.mydomain.com" which point to IP 192.168.x.x. but there is no different
  -e ROUNDCUBEMAIL_SMTP_SERVER=localhost \
  -e ROUNDCUBEMAIL_DB_TYPE=sqlite \
  roundcube/roundcubemail
```
and the run log is as follows
```
roundcubemail found in /var/www/html - installing update...
Target installation already in version 1.6.9. Do you want to update again? (y/N)
Copying files to target location...done.

Running update script at target...
Executing database schema update.
/usr/bin/composer
Executing /usr/bin/composer to update dependencies...
Composer could not detect the root package (roundcube/roundcubemail) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading guzzlehttp/promises (2.0.3 => 2.0.4)
  - Upgrading symfony/deprecation-contracts (v2.5.3 => v3.5.0)
Writing lock file
Installing dependencies from lock file
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading symfony/deprecation-contracts (v3.5.0)
  - Downloading guzzlehttp/promises (2.0.4)
 0/2 [>---------------------------]   0%
 1/2 [==============>-------------]  50%
 2/2 [============================] 100%
  - Upgrading symfony/deprecation-contracts (v2.5.3 => v3.5.0): Extracting archive
  - Upgrading guzzlehttp/promises (2.0.3 => 2.0.4): Extracting archive
 0/2 [>---------------------------]   0%
 2/2 [============================] 100%
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
This instance of Roundcube is up-to-date.
Have fun!
All done.
Composer could not detect the root package (roundcube/roundcubemail) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Write Docker config to /var/www/html/config/config.docker.inc.php
Checking for database schema updates...
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Nov 17 16:59:44.638627 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.1.30 configured -- resuming normal operations
[Sun Nov 17 16:59:44.638660 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.0.246 - - [17/Nov/2024:17:00:36 +0000] "POST /?_task=login HTTP/1.1" 401 3199 "http://192.168.0.243/?_task=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0"
```
Can someone please tell me where the problem is?

**Comment by pabzm** [comment]
Did you try twice to login? The error message might be due to your first request not having the expected CSRF-token, which gets resolved after the first page reload.

If you still can't log in:
* try to run bash in the roundcube-container and use telnet to connect to your mail server to verify that the connection is available.
* set `imap_debug` to true in Roundcubemail's configuration and check the logs for related messages

**Comment by EnergeticMrMask** [comment]
> Did you try twice to login? The error message might be due to your first request not having the expected CSRF-token, which gets resolved after the first page reload.
> 
> If you still can't log in:
> 
> * try to run bash in the roundcube-container and use telnet to connect to your mail server to verify that the connection is available.
> * set `imap_debug` to true in Roundcubemail's configuration and check the logs for related messages

Yes I tried login many times. This prompt appears even every time I refresh the login page.
I tried using `EMClient` to connect to my mail server from other devices on the local network, and it worked. Therefore, `RoundcubeMail`, running on the same device as the mail server, should also be able to connect to the mail server.
I added `imap_debug = true` to the `config.inc.php` file in `/var/www/html/config/` and then recreated the container with the `imap_debug = true` parameter added. However, I couldn't find the IMAP logs. The `/var/www/html/logs/` folder has no files except for a hidden file named `.htaccess`, which I believe has nothing to do with IMAP. The `/var/log/` folder contains files such as `alternatives.log`, `access.log`, `error.log`, `history.log`, and `term.log`, which have valid information but no content related to imap_debug. Could you provide more detailed instructions?

**Comment by pabzm** [comment]
> I tried using EMClient to connect to my mail server from other devices on the local network, and it worked 

With which settings? Please tell more details about what you're trying.

> Therefore, RoundcubeMail, running on the same device as the mail server, should also be able to connect to the mail server.

There's a "should" in your sentence. Please check if that is actually the case (e.g. by using telnet or `curl imaps://$hostname:$port`.

Where the logs end up depends on your configuration. Please post each file in both, the `config/` and the `/var/roundcube/config` folders, *from inside* the container after starting it – please redact passwords and usernames but nothing else and post the whole file.

**Comment by EnergeticMrMask** [comment]
I have decided to temporarily stop using docker to selfhost RoundcubMail and switch to another project which include RoundcubeMail for the convenience of deployment.
As such, I regret that I will not be able to provide further feedback at this moment. You can close this issue if you want.

**Comment by pabzm** [comment]
Thank you for the notice, I'll close this because I won't be able to debug it alone.
