### ISSUE TITLE
php-ext-install soap error

### ISSUE THREAD

**Issue by emyfr** [roundcube/roundcubemail-docker#286]
Hi, I need to to build a image with soap module.

When I try to launch: 'docker-php-ext-install soap' I get the following error:

In file included from /usr/src/php/ext/soap/soap.c:22:
/usr/src/php/ext/soap/php_soap.h:24:10: fatal error: ext/standard/info.h: No such file or directory
   24 | #include "ext/standard/info.h"

I tried to do the same with the php:8.1-apache image and everything works fine.

Thanks
Emiliano

**Comment by pabzm** [comment]
Thank you for you report! I can confirm that this is broken. In `:1.6.8-apache` it works, so something broke it in between.
