### ISSUE TITLE
PHP Fatal error:  Allowed memory exhausted due to self include

### ISSUE THREAD

**Issue by madmath03** [roundcube/roundcubemail-docker#29]
On first startup, `docker-entrypoint.sh` initializes `config.inc.php` but then includes all PHP files, including itself in the process:
https://github.com/roundcube/roundcubemail-docker/blob/65b131859294c08bf33ce35bb191e8ff6e957bd6/php-apache/docker-entrypoint.sh#L76

**Comment by aspettl** [comment]
In your setup, is `/var/www/html/config` actually the same folder as `/var/roundcube/config`? Then this is the problem.

I put my config files into `/var/roundcube/config` (as the readme says) and did not touch anything in `/var/www/html/config`. The generation of the main config file works as intended - i.e., no including itself or e.g. `defaults.inc.php`.

**Comment by madmath03** [comment]
@aspettl Damn... you're right. I had misconfigured the mapped volumes and ended up mapping the `/var/www/html/config` and `/var/roundcube/config` on the same local folder.
Thanks a lot for pointing that out.

@thomascube The PR does not break anything, I guess it is a bit more secure one were to pass an invalid value, but it is not necessary anymore.
It's your choice to merge this or not.
