### ISSUE TITLE
echo "$config['enigma_pgp_homedir'] is not correctly escaped

### ISSUE THREAD

**Issue by logopk** [roundcube/roundcubemail-docker#295]
https://github.com/roundcube/roundcubemail-docker/blame/44bd59fa0ca61979b9577368681579873f962d84/fpm/docker-entrypoint.sh#L155

Compare the two lines!

docker-entrypoint.sh:    echo "\$config['spellcheck_uri'] = '${ROUNDCUBEMAIL_SPELLCHECK_URI}';" >> config/config.docker.inc.php
docker-entrypoint.sh:    echo "$config['enigma_pgp_homedir'] = '/var/roundcube/enigma';" >> config/config.docker.inc.php

Startup with enigma fails since latest release and cannot be taken back as image is not versioned  :-(

**Comment by pabzm** [comment]
Thank you for your report! This is indeed broken, sorry for that! Using the "enigma" plugin wasn't part of your tests, I'll change that.

> image is not versioned

You can always refer to an image by ID, those change with every update. The ID of the latest image from before merging the broken change is  `49d4016899c6508744e0c4b8a8c5f0c2f02f953ecef483b48c648eaa0d80be62`, which you can reference with `docker.io/roundcube/roundcubemail@sha256:49d4016899c6508744e0c4b8a8c5f0c2f02f953ecef483b48c648eaa0d80be62`
