### ISSUE TITLE
IMAP login not working

### ISSUE THREAD

**Issue by HanSyt** [roundcube/roundcubemail-docker#305]
I haven roundcube:latest installed on my system with:

# Start roundcube
docker run -d \
  --name roundcubemail \
  --restart=unless-stopped \
  -e ROUNDCUBEMAIL_DEFAULT_HOST=ssl://webmail.sytsma.co.uk \
  -e ROUNDCUBEMAIL_DEFAULT_PORT=993 \
  -e ROUNDCUBEMAIL_SMTP_SERVER=tls://smtp.sytsma.co.uk \
  -e ROUNDCUBEMAIL_SMTP_PORT=587 \
  -e ROUNDCUBEMAIL_SKIN=larry \
  -e ROUNDCUBEMAIL_INSTALL_PLUGINS=1 \
  -p 85:80 \
  -v roundcube-conf:/var/www/html/config \
  -v roundcube-db:/var/roundcube/db \
  -v roundcube-skins:/var/www/html/skins \
  -v roundcube-plugins:/var/www/html/plugins \
  roundcube/roundcubemail

Day 1: works like a charm, snappy and fully operational.
Day 2: I can connect to the webmail server, snappy, however login in is a problem, or it is very slow, or I can't login.

conditions:
 webmail.sytsma.co.uk is a nginx accelerator (https) in my dmz and connects through a router to the docker container with the http protocol.
The imap and smtp addresses are only available on the inside network (or vpn) . (using split DNS).

I can reproduce this on 2 servers, exactly the same behaviour (why after one day?).
However, if I have the roundcubemail running locally on the same server the problem doesn't occur, so it seems to be docker / image related. 

What I have seen with tcpdump / wireshark :  connection on port 993 ends up with retransmissions, like in the screenshot
![Screenshot_20241222_123120](https://github.com/user-attachments/assets/61adf1d9-e9dd-4a70-8077-f04b6fb8b139)

My mailserver is running debian 12, bookwork, fully patched, the docker1 server is also running Debian 12, bookworm, fully patched. 
So what is causing this network behaviour - switching off firewalls (iptables -F) does is not helpfulll.

Any clues?

I have the full pcap file available if needed

**Comment by HanSyt** [comment]
Solved it.. my stupid lack of knowledge of Docker. Brought my bind server in docker on the same host. The roundcube pod got /etc/resolv.conf copied from the host before bind was brought into docker.
Although the name server is still the same IP 127.roundcube => host =>  IP127.bind VV is not working. The bind secondary on another server is working however.

Made /etc/docker/daemon.json with the appropriate nameservers in it. Restarted the deamon and finally reloaded the pod image and Roundcube is working smoothly again.

**Comment by pabzm** [comment]
Thank you for explaining what solved your issue! It might help others who run into the same issue in the future!
