### ISSUE TITLE
Please rebuild against latest php version 

### ISSUE THREAD

**Issue by dupgit** [roundcube/roundcubemail-docker#32]
Hi,

I'm willing to update my roundcube docker images to the latest php version (latest 7.1 as selected in your images). Please can you rebuild an update docker hub accordingly ?

**Comment by thomascube** [comment]
New images with version 1.3.7 pushed. The next release is on the way

**Comment by dupgit** [comment]
Thanks :-)

**Comment by thomascube** [comment]
Latest version 1.3.8 now available on Docker hub.
