### ISSUE TITLE
Why is the source not initially extracted to /var/www/html ?

### ISSUE THREAD

**Issue by AubreyHewes** [roundcube/roundcubemail-docker#33]
The extra step to copy the source on container start just seems redundant. Also it removes the possibility for downstream images to replace files. i.e. customize.
Extracting it to the expected location removes having to copy it on container start and also allows downstream to replace files.

i.e. replace the favicon.ico in `skins/larry` without having to create a new skin (I know that from 1.4 this can be done via `skin_logo` though I am talking about 1.3)..

**Comment by thomascube** [comment]
I don't get the point. You can still replace images in `/usr/src/roundcubemail` where the sources are copied from, no?

**Comment by thomascube** [comment]
No feedback. Closing.
