### ISSUE TITLE
ROUNDCUBEMAIL_DEFAULT_HOST/default_host with array

### ISSUE THREAD

**Issue by christianbur** [roundcube/roundcubemail-docker#37]
if you use an array in the environment vairable ROUNDCUBEMAIL_DEFAULT_HOST this does not work, because single quotation marks are made around the variable content. 

https://github.com/roundcube/roundcubemail/wiki/Configuration
```
     environment:
      - "ROUNDCUBEMAIL_DEFAULT_HOST=array('mail.example.com', 'webmail.example.com', 'ssl://mail.example.com:993')"
```

```
 # docker exec -it roundcube_roundcube_1 bash -c "cat /var/www/html/config/config.inc.php"
<?php
    $config['db_dsnw'] = 'qlite:////var/www/html/db/sqlite.db?mode=0646';
    $config['db_dsnr'] = '';
    $config['default_host'] = 'array('mail.example.com', 'webmail.example.com', 'ssl://mail.example.com:993')';
```

the error in the logfile
```
# dc logs
...
roundcube_1  | PHP Parse error:  syntax error, unexpected 'mail' (T_STRING) in /var/www/html/config/config.inc.php on line 4
roundcube_1  | PHP Parse error:  syntax error, unexpected 'mail' (T_STRING) in /var/www/html/config/config.inc.php on line 4
```

**Comment by thomascube** [comment]
The `ROUNDCUBEMAIL_DEFAULT_HOST` parameter is not intended for multi-host configuration but only for a simple basic setup. You can override the config with your custom configuration files. See the [README](https://github.com/roundcube/roundcubemail-docker#advanced-configuration) file.
