### ISSUE TITLE
Update trusted CA certs in container?

### ISSUE THREAD

**Issue by reibuehl** [roundcube/roundcubemail-docker#39]
My mailserver uses a certificate from CAcert.org that seems to be not trusted by the apache/php in the roundcube container. Is there a persistent way to add the cert to the trusted ca certs?

**Comment by thomascube** [comment]
No idea but this is not actually a Roundcube related problem but general. Please try to get help from the php docker folks directly.

**Comment by reibuehl** [comment]
It turned out to be a Roundcube related issue: The default in the container seems to be to do IMAP server cert verification. If the IMAP server CA is unknown, you need to use a custom configuration by mounting a custom config file as a volume:

` volumes:
    - ./config:/var/roundcube/config/
`

Then put cacert.org.pem and config.php into that directory and use the following settings in config.php:

`<?php

// IMAP socket context options
// See http://php.net/manual/en/context.ssl.php
// The example below enables server certificate validation
$config['imap_conn_options'] = array(
  'ssl'         => array(
     'verify_peer'  => true,
     'verify_depth' => 3,
     'cafile'       => '/var/roundcube/config/cacert.org.pem',
   ),
 );
`

After this, the connection works to the IMAP server with a CAcert.org certificate.
