### ISSUE TITLE
Documentation on how to install non-builtin plugins in container?

### ISSUE THREAD

**Issue by reibuehl** [roundcube/roundcubemail-docker#40]
Is there some form of documentation on how to best install 3rd party plugins from https://plugins.roundcube.net/ into the container?

**Comment by reibuehl** [comment]
It seems that composer is partly installed in the docker image. I see that there is a composer.json file under /usr/src/roundcubemail/vendor/roundcube/plugin-installer but composer.phar seems to be missing. Is this the right way to go forward? Do I need to install composer.phar in that directory and then run it from the Dockerfile?

**Comment by thomascube** [comment]
No, composer is not part of the image. Honestly, the Docker image is not prepare for custom plugin installations. I suggest to mount the `/var/www/html` as volume and perform plugin installation from outside the container.

If done inside the container, just follow the instructions listed at https://plugins.roundcube.net

```
$ docker exec -it ed5010a7eddc /bin/bash
# apt-get update
# apt-get install git
# curl -s https://getcomposer.org/installer | php
# mv composer.json-dist composer.json
# php composer.phar require johndoh/contextmenu --no-update
# php composer.phar update --no-dev
```

Please check if that works for you. We'll then create a wiki page once the process is confirmed to work.

**Comment by madmath03** [comment]
Like @thomascube mentioned, the best is probably to do it outside the container and simply mount the volume.
I've done it several times and here is how I've done it:
* First mount the `/var/www/html` volume locally. With docker-compose, it looks like this:
```
