### ISSUE TITLE
Add 1.4-rc1 and 1.3.9 tag to docker image

### ISSUE THREAD

**Issue by madmath03** [roundcube/roundcubemail-docker#42]
Everything is in the title.

**Comment by wedi** [comment]
Wanted to create a pull request but there is already one that fixes this issue:
https://github.com/roundcube/roundcubemail-docker/pull/43

**Comment by thomascube** [comment]
PR merged, I assume the ticket can be closed. We won't create Docker images for beta/rc versions.

**Comment by madmath03** [comment]
> We won't create Docker images for beta/rc versions.

You say that but the `elastic` tag on Dockerhub is using the 1.4-beta... which is why I thought you were going to provide beta/rc versions. That's not a issue in itself, just a bit confusing.

**Comment by thomascube** [comment]
Elastic was an exception because we wanted an image people can use to test the new theme. But that doesn’t mean we do it for all beta version. We also didn’t follow the versioning scheme for the tags.
