### ISSUE TITLE
Docker with enigma plugin as volume: Application Error (600): Enigma plugin: Keys directory isn't writeable: /var/www/html/plugins/enigma/home

### ISSUE THREAD

**Issue by erikderzweite** [roundcube/roundcubemail-docker#45]
I have installed roundcube as docker image behind traefik. 

When I try to mount plugins/enigma as volume in roundcube container, but on each restart the enigma/home/ user and permissions are being reset. uid:gis is 501:80

This results in "Application Error (600): Enigma plugin: Keys directory isn't writeable: /var/www/html/plugins/enigma/home"

Interesting thing is: my enigma/home/user@domain.tld folders have owner "www-data:www-data" and work fine. It's only enigma/home that's causing this problem. I need to chown www-data:www-data home after each container restart.

mounting plugins/ folder as a volume didn't help.

**Comment by thomascube** [comment]
Consider setting the enigma home dir to a path outside of Roundcube's root directory via custom config:
```
$config['enigma_pgp_homedir'] = '/path/mounted/as/volume';
```

**Comment by erikderzweite** [comment]
Mounted to /var/tmp/enigma, that seems to work, thanks!
