### ISSUE TITLE
Support for secrets

### ISSUE THREAD

**Issue by pschichtel** [roundcube/roundcubemail-docker#46]
It would be nice if the container supported secrets for e.g. the database credentials.

**Comment by thomascube** [comment]
We gladly accept pull requests with the required changes to the Dockerfile :-)

**Comment by thomascube** [comment]
https://docs.docker.com/engine/swarm/secrets/

**Comment by thomascube** [comment]
I have no experience with Docker swarm and secrets but support has been added (see [README](/roundcube/roundcubemail-docker/blob/master/README.md#docker-secrets)). Please review and re-open this issue if it doesn't work as you expected it.
