### ISSUE TITLE
Use a Dockerfile.template to generate both php variant

### ISSUE THREAD

**Issue by madmath03** [roundcube/roundcubemail-docker#5]
There isn't many differences between the apache and fpm version, and the entrypoint is identical.

Using a Dockerfile.template with an `update.sh` script to generate / update the variants would make maintenance much easier.

For reference:
- https://github.com/nextcloud/docker/blob/master/update.sh
- https://github.com/nextcloud/docker/blob/master/Dockerfile-debian.template

**Comment by J0WI** [comment]
See #20.
Once https://github.com/roundcube/roundcubemail/issues/5827 @docker-library-bot (needs write access) can update the images automatically.

**Comment by madmath03** [comment]
Reopen until #55 merged.
