### ISSUE TITLE
Rebuild Docker Images

### ISSUE THREAD

**Issue by davepage-mcr** [roundcube/roundcubemail-docker#56]
The docker images available at https://hub.docker.com/r/roundcube/roundcubemail are based on old versions of the "upstream" PHP images. This means that they inherit old, broken package repositories (which I think is caused by the Buster release process).

Cloning and building my own `roundcube/roundcubemail:latest-fpm` fixes the problem I'm seeing with building my own container based on this (incorporating some extra plugins).

I would personally recommend scheduling periodic rebuilds of the containers - we do this nightly to make sure upstream security updates etc. are incorporated, then pushed to our internal container registry.

**Comment by thomascube** [comment]
Autobuilds have now been configured: https://hub.docker.com/r/roundcube/roundcubemail/builds
They should also trigger on updates of the base images.
