### ISSUE TITLE
Feature Request to add roundcube plugins extra (sieverules etc.)

### ISSUE THREAD

**Issue by zem** [roundcube/roundcubemail-docker#60]
please add roundcube plugins extra to this image, I am especially missing the sieve plugin, and it would be awesome to be able to activate it quickly. 

regards 

     Hans

**Comment by madmath03** [comment]
Hello @zem,

It's already possible to easily activate plugins : just use the `ROUNDCUBEMAIL_PLUGINS` as described in the README.
For instance:
```
ROUNDCUBEMAIL_PLUGINS=archive,attachment_reminder,emoticons,identicon,markasjunk,newmail_notifier,password,vcard_attachments,zipdownload```

Regarding Sieve, you will need to install Net_Sieve in the Dockerfile : 
```
pear install Net_Sieve
```
Here is a Docker container using this repo as the base and enabling extra plugins like Sieve : https://github.com/Monogramm/docker-roundcube/blob/master/Dockerfile-debian.template

Will have to check with @thomascube if he is okay with enabling more plugins by default and if so, which ones.

**Comment by thomascube** [comment]
> Regarding Sieve, you will need to install Net_Sieve in the Dockerfile

The image should contain the complete package of Roundcube which is supposed to contain all dependencies for packaged plugins (including Net_Sieve for managesieve). Thus enabling `managesieve` via `ROUNDCUBEMAIL_PLUGINS` should IMO work.

**Comment by alecpl** [comment]
ps. sieverules plugin is no longer maintained, use managesieve plugin.

**Comment by thomascube** [comment]
No feedback. Closing.
