### ISSUE TITLE
Need to set the allow_self_signed variable

### ISSUE THREAD

**Issue by Aphris-Karu** [roundcube/roundcubemail-docker#62]
When it sets up tls we need an env var to set allow_self_signed = true. So that it will accept the self signed certs on the imap server.

**Comment by thomascube** [comment]
You can overwrite any config option you'd like by providing a custom config file to your container. See the [Advanced configuration](https://github.com/roundcube/roundcubemail-docker/blob/master/README.md#advanced-configuration) section. The option in question is [`imap_conn_options`](https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L156).

Please understand that we don't map all possible options to Docker container variables.
