### ISSUE TITLE
Missing 1.4.0 tags

### ISSUE THREAD

**Issue by fridtjof** [roundcube/roundcubemail-docker#66]
I don't want to use latest in my compose files, can you add a tag for the new 1.4.0 release please?

**Comment by thomascube** [comment]
Done: https://hub.docker.com/r/roundcube/roundcubemail/tags

However, I suggest to pull the 1.4.x tag instead in order to get constant updates to the image. Read more in the "Tags and Variants" section.

**Comment by fridtjof** [comment]
Will do, thank you!
