### ISSUE TITLE
install-jsdeps.sh not run?

### ISSUE THREAD

**Issue by tomuta** [roundcube/roundcubemail-docker#67]
I'm using the `latest` tag and I think it's missing some dependencies. I enabled the `password` plugin, but saving the password fails like this:

> roundcube      | errors: <31e4b198> PHP Error: Request security check failed (POST /?_task=settings&_action=refresh)172.18.0.1 - - [11/Nov/2019:22:16:47 +0000] "POST /?_task=settings&_action=refresh HTTP/1.1" 403 502 "https://xxxxxxxxxxxxx/?_task=settings&_action=plugin.password-save" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"

Seems like I'm running into roundcube/roundcubemail#5579. Should the Dockerfile be running bin/install-jsdeps.sh, or the entry point? I'm worried that if I run this in the container manually, it'll get wiped out next time I pull?

**Comment by thomascube** [comment]
That error doesn't seem related to jsdeps (which anyway are in there). The error is logged for the `_action=refresh` request and not the password saving step. I'll try to investigate this.

**Comment by tomuta** [comment]
I'm not sure what caused this, I think it had to do with the html folder being in a volume and things not properly upgrading. Since implementing #71 I no longer need the html folder in a volume as I can generate the entire configuration on-the-fly, and I haven't seen the issue since. So, I believe it was somehow user error on my side.
