### ISSUE TITLE
1.4.0: Default theme still larry?

### ISSUE THREAD

**Issue by tomuta** [roundcube/roundcubemail-docker#68]
After pulling `latest` (which now is 1.4.0) I noticed that the login screen is still the old theme. Looks like it's hardcoded to "larry", still. Shouldn't it default to "elastic" now? Maybe an environment variable `ROUNDCUBEMAIL_SKIN` would make sense?

**Comment by thomascube** [comment]
Yes, we hard-coded the larry skin in order to avoid surprises to those regularly pulling the latest image. I'm not aware of a commonly used way to communicate release notes with Docker images/tags. A specific env variable would indeed make sense and we'll consider that.
