### ISSUE TITLE
Unable to log in after upgrade from 1.3.10 to 1.4.0

### ISSUE THREAD

**Issue by bovender** [roundcube/roundcubemail-docker#72]
After upgrading from 1.3.10 to 1.4.0 (using a Docker container), I am unable to log in to my Roundcube instance. I did not change the config file. When I revert the Docker container tag back to 1.3.10, it works again.

The log shows this error:

    Could not connect to ssl://MYDOMAIN:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 196

What might be the problem? The config file is the always the same, it is on a Docker volume. Is there a configuration setting that needs to be changed when upgrading to 1.4.0?

**Comment by thomascube** [comment]
The "Unknown reason" error likely comes from openssl not being able to verify the SSL vert of your IMAP server. Do you use a self-signed cert or one from a non-official issuer?

The 1.4.0 tag is based on php:7.3 images whereas the older 1.3.x tags used php:7.2 base images. Maybe the PHP distro changes some defaults in their images.

**Comment by bovender** [comment]
My IMAP server presents a valid (not expired) Letsencrypt certificate. The recent comment in the issue referenced above suggests that it is not related to the Docker container after all.

**Comment by thomascube** [comment]
Connection fails with the error `routines:tls_process_server_certificate:certificate verify failed` which I'm now trying to investigate. When disabling cert checks (verify_peer = false), connection should works but that's not the right solution.

Strange fact: connecting with `curl` which links to the same libssl as PHP does seems to work and accept the certificate.

Unfortunately downgrading to php:7.2-apache base image didn't solve the issue. More investigation is needed.

**Comment by nsk7even** [comment]
I'm new to roundcubemail-docker and are having this issue as well - how to use the `verify_peer = false` switch to disable the cert check?
I created a `customcfg.inc.php` file in the automatically created `www/config/` folder on the host with the following content:

    <?php
        $config['verify_peer'] = false;

But it still fails.

**Comment by thomascube** [comment]
The `verify_peer` flag needs to be set to the `imap_conn_options` and `smtp_conn_options` config options:
https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L160
https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L310

**Comment by nsk7even** [comment]
Thank you for this information, I tried this, but it didn't worked either, I'm afraid. I don't know what I did wrong. So I switched to mailpile. But keep up the good works!

**Comment by thomascube** [comment]
Please try with the latest images. We just upgraded to PHP 7.4 base images and with the following custom config, I was able to connect to a mail server using an Letsecrypt cert:
```
$config['imap_conn_options'] = [
  'ssl' => [
    'verify_peer'  => true,
  ],
];
```

**Comment by thomascube** [comment]
> WORKS, THANK YOU!!

I now consider this issue resolved.

**Comment by Fernien** [comment]
@thomascube I maybe have the same issue and i think i did what you explained. Can you maybe a describe a bit more in depth what you did? Not sure if i did something wrong

**Comment by sylvestre** [comment]
I had a similar issue, using "localhost" instead of the hostname.

the following fixed it:
```
    $config['smtp_conn_options'] = [
        'ssl'         => [
            'verify_peer_name'  => false,
        ],
    ];
```
