### ISSUE TITLE
Security problem: "db/sqlite.db"

### ISSUE THREAD

**Issue by salesgroup** [roundcube/roundcubemail-docker#76]
It's possible to get the "db/sqlite.db" file using:
http://domain.com/db/sqlite.db

Please add "db|" in the .htaccess, eg:
 RewriteRule ^/?(\.git|\.tx|SQL|db|bin|config|logs|temp|tests|vendor|program\/(include|lib|localization|steps)) - [F]

**Comment by thomascube** [comment]
The use of SQLite is actually not intended for production systems but it should nevertheless be secure. The better solution would be to store the DB on a separate volume outside of the webserver's document root. That would also allow to persist the data when killing a container and to share the DB among multiple instances.

**Comment by thomascube** [comment]
FWIW: you can change the db location using the `ROUNDCUBEMAIL_DB_DIR` parameter.

**Comment by alecpl** [comment]
Why not set the document root to public_html?
