### ISSUE TITLE
When will tag "latest" change from 1.3.x to 1.4.x?

### ISSUE THREAD

**Issue by reibuehl** [roundcube/roundcubemail-docker#77]
Currently, the "latest" tag of the docker image seems to point to the latest 1.3.x build. When will this be changed to the now stable 1.4.x series and are there any manual steps needed to move from 1.3.x container to 1.4.x or can this be done by just pulling the new image?

**Comment by thomascube** [comment]
The `latest` tag is actually meant to refer to 1.4.x but was unintentionally changed by build hooks.
