### ISSUE TITLE
No possibility to create config for managesieve plugin

### ISSUE THREAD

**Issue by sgofferj** [roundcube/roundcubemail-docker#79]
I activated the managesieve plugin which tries to connect to localhost:4190. I checked through /docker-entrypoint.sh as well as the managesieve plugin code and there seems to be no way to define managesieve_host except editing the config in the volume - which is a bit contrary to the idea of containers.

I'd like to suggest/request adding the respective options for managesieve to /docker-entrypoint.sh.

**Comment by robin-thoni** [comment]
I would say the usual pattern is to make your own `Dockerfile`:
```
FROM roundcube/roundcube:x.y

COPY ./config/ /usr/src/roundcubemail/
```

With `./config/`:
```
- config
  - plugins
    - managesieve
      - config
        - config.inc.php
```

The drawback is that you have to completely remove/recreate the container AND the volume when modifying config files, as the original `Dockerfile` is using a `VOLUME` for RC install dir, which is kinda non-sense to me...

**Comment by thomascube** [comment]
We don't want to map all possible config options (from a wide variety of plugins) to Docker container variables. But you can create your own custom config file for your setup. See the [Advanced configuration section](https://github.com/roundcube/roundcubemail-docker/blob/master/README.md#advanced-configuration).

And it's also not necessary to create your own docker image for this. Simply create a config file named `managesieve.inc.php` in a volume linked with `/var/roundcube/config` and adjust the settings you need there.

**Comment by sgofferj** [comment]
Doesn't seem to work...

I copied the config.inc.php.dist from the plugin directory to a respective volume which I bind mounted. In the config I changed the managesieve host to the proper value. I opened a shell in the container and the managesieve.inc.php is in /var/roundcube/config inside the container and his has the correct content. Still...:

```
172.21.1.15 - - [18/Feb/2020:11:43:21 +0000] "GET /?_task=settings HTTP/1.1" 200 3452 "https://webmail.gofferje.net/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
errors: <848873e8> PHP Error: Cannot assign requested address (GET /?_task=settings&_action=plugin.managesieve)errors: <848873e8> PHP Error: Unable to connect to managesieve on localhost:4190 in /var/www/html/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 223 (GET /?_task=settings&_action=plugin.managesieve)errors: <848873e8> PHP Error: Not currently in AUTHORISATION state (GET /?_task=settings&_action=plugin.managesieve)errors: <848873e8> PHP Error: Not currently connected (GET /?_task=settings&_action=plugin.managesieve)
```

**Comment by sgofferj** [comment]
Never mind. After recreating the container it works now. Thanks.
