### ISSUE TITLE
Updates to roundcubemail not published on roundcubemail-docker

### ISSUE THREAD

**Issue by adlerweb** [roundcube/roundcubemail-docker#8]
This docker repository as well as the official image on hub.docker.com are several versions behind and include known security vulnerabilities.

Changing `ENV ROUNDCUBEMAIL_VERSION` seems to work, maybe this could be automated to be run and posted as soon as there is a new push on [roundcubemail/releases](https://github.com/roundcube/) as suggested in #1.

**Comment by thomascube** [comment]
Pushed latest version to Docker hub: https://hub.docker.com/r/roundcube/roundcubemail/tags/

**Comment by thomascube** [comment]
Will configure automated builds on Docker hub once our Docker images are considered "final". We're still in the process of finding the right way to deliver Roundcube via Docker. There are many ways and opinions how to do it.

**Comment by J0WI** [comment]
The FPM variant is not yet published on Dockerhub at all.

**Comment by adlerweb** [comment]
Maybe you should add a note over on Docker hub to clarify these are not final for the meantime

**Comment by compuguy** [comment]
Wondering when the docker hub builds will be updated, they just fixed another issue with this image in #27 .

**Comment by J0WI** [comment]
There are also some outstanding security updates for the underlying image: #32

**Comment by J0WI** [comment]
@thomascube the image lacks many security patches from Debian and PHP. Please trigger rebuilds.

**Comment by J0WI** [comment]
Or maybe @alecpl has time to trigger a rebuild...

**Comment by thomascube** [comment]
New images for Roundcube 1.3.8 have been pushed.

**Comment by madmath03** [comment]
Based on @thomascube comment in https://github.com/roundcube/roundcubemail-docker/issues/56#issuecomment-509608441, autobuilds have been enabled so this can be closed.

**Comment by thomascube** [comment]
The ticket requests that "Updates to roundcubemail" (I assume new releases) are automatically propagated to this repo (-> updating `ROUNDCUBEMAIL_VERSION`) which shall then trigger automated builds. I think we're not there yet.

**Comment by madmath03** [comment]
Indeed, if this is what was intended then we're not there yet.
This would actually require an external service to be triggered on each new rouncubemail release.

By the way, even if it would not solve this completely, the PR #55 would greatly help :
* you would just need to execute the `update.sh` script, which would update all the dockerfiles with the latest release, and then push the changes
* the automated docker builds would catch the github commit and build the new images for the existing tags and you would just need to add the new tag

Even if it's not 100% automatic, it would only be a matter of minutes to push new releases.

What do you think ?

**Comment by J0WI** [comment]
Or you just solve #31 and let the @docker-library-bot take care of updates.

**Comment by thomascube** [comment]
I agree that PR #55 would greatly help here. However, this still doesn't work on my Mac with Bash 5.0 :-(

**Comment by J0WI** [comment]
You also need `curl`. What error do you get with it?
