### ISSUE TITLE
Container from custom image : /var/roundcube/config empty

### ISSUE THREAD

**Issue by Bepsi** [roundcube/roundcubemail-docker#80]
Hi,

With Docker 1.13.1 (I know ... it's an old version) I build a custom Roundcube image with the following Dockerfile:

FROM roundcube/roundcubemail:1.4.2-apache

MAINTAINER ASR-INFORMATIQUE`
LABEL version="1.0.4"
LABEL description="Container RoundcubeMail ASR"
ENV ROUNDCUBEMAIL_DEFAULT_HOST xxxx
ENV ROUNDCUBEMAIL_DEFAULT_PORT xxxx
ENV ROUNDCUBEMAIL_SMTP_SERVER xxxx
ENV ROUNDCUBEMAIL_SMTP_PORT xxxx
ENV ROUNDCUBEMAIL_DB_TYPE xxxx
ENV ROUNDCUBEMAIL_DB_HOST rc-db
ENV ROUNDCUBEMAIL_DB_USER xxxxx
ENV ROUNDCUBEMAIL_DB_PASSWORD xxxxx
ENV ROUNDCUBEMAIL_PLUGINS "archive,zipdownload,html5_notifier,twofactor_gauthenticator,autologon,filters,user_config"

RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        git \
        unzip \
    ; \
    apt-get clean; \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer; \
    mv /usr/src/roundcubemail/composer.json-dist /usr/src/roundcubemail/composer.json

RUN composer \
        --working-dir=/usr/src/roundcubemail/ \
        --prefer-dist --prefer-stable \
        --no-update \
        --no-interaction \
        --optimize-autoloader --apcu-autoloader \
        require \
            kitist/html5_notifier:dev-master \
            roundcube/filters:dev-filters-2.2.1 \
            sbehuret/user_config:dev-master \
    ; \
    composer \
        --working-dir=/usr/src/roundcubemail/ \
        --prefer-dist --no-dev \
        --no-interaction \
        --optimize-autoloader --apcu-autoloader \
        update
RUN git clone https://github.com/alexandregz/twofactor_gauthenticator.git /usr/src/roundcubemail/plugins/twofactor_gauthenticator
COPY asr /usr/src/roundcubemail/skins/asr
COPY asr-roundcube.inc.php /var/roundcube/config/asr-roundcube.inc.php

In this image, I can find the file /var/roundcube/conf/asr-roundcube.inc.php.

When I create a container from this image, the /var/roundcube/config directory is empty.

Can you help me ?

Thx.

**Comment by thomascube** [comment]
This is probably because `/var/roundcube/config` is defined as volume in our [Dockerfile](https://github.com/roundcube/roundcubemail-docker/blob/master/apache/Dockerfile#L51) and therefore linked to Docker's storage system. That directory is intended to contain custom config files provided by the environment (not the Docker image itself).

Just copy your `asr-roundcube.inc.php` config file to a directory which you link as volume when starting your docker image instead.

**Comment by thomascube** [comment]
No more feedback.
