### ISSUE TITLE
Folders not sorted due to lack of locales

### ISSUE THREAD

**Issue by bwdutton** [roundcube/roundcubemail-docker#81]
The setlocale() call here:
https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail.php#L188
doesn't do anything in the docker image as there is no locale support. I locally changed this line:
https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_imap.php#L4426
from strcoll() to strcasecmp() to get the desired effect. Possible solutions would be:
1. to switch to a base image with locale support
2. add a sort flag that the docker build can enable to use strcasecmp() instead of strcoll()
3. leave it as is

**Comment by bwdutton** [comment]
I didn't realize there were Alpine and Debian images originally. Debian supports locales easy enough so I created a PR.

**Comment by thomascube** [comment]
We might consider defining a default value for `ROUNDCUBEMAIL_LOCALE`

**Comment by bwdutton** [comment]
Sure, I set it to en_US
