### ISSUE TITLE
Increase Maximum allowed file size

### ISSUE THREAD

**Issue by adrian-amaglio** [roundcube/roundcubemail-docker#86]
Hello,

I’m trying to increase the maximum file size for attachments.
Currently, the maximum allowed size displayed in the Options and attachments panel next to the mail composition form is : `5.0M`.
I added the `ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M` environment variable but the displayed limit is now `18.0M`.

Where does this 18.0 figure come from, and how can I raise the limit to 25M ?

- image: `roundcube/roundcubemail:1.4.x-apache` (just pulled)
- OS: debian 9.12
- Docker version 19.03.7

**Comment by thomascube** [comment]
The attachment file size limit is also influenced by the `max_message_size` config option in Roundcube. See Roundcube [issue #7105](https://github.com/roundcube/roundcubemail/issues/7105). That option, however, is set to a default value of 100M.

**Comment by dotcomUNDERGROUND** [comment]
I have the following added to my custom.php 

`$config['upload_max_filesize'] = '50M';`
`$config['max_message_size'] = '50M';`
`$config['max_filesize'] = '50M';`

I still see 5mb upload limit.

**Comment by brentcetinich** [comment]
In my case I also had to increase it on nginx using a custom nginx.

In docker-compose.yml:

`  roundcubenginx:
    image: nginx:latest
    container_name: roundcubenginx
    restart: unless-stopped
    ports:
      - 9009:80
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - roundcubemail
    links:
      - roundcubemail
    volumes:
      - ./www:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
      # Provide a custom nginx conf
      - ./nginx/custom-nginx.conf:/etc/nginx/nginx.conf:ro
`

Inside ./nginx/custom-nginx.conf

`cat custom-nginx.conf 
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    client_max_body_size 24000M;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
`
