### ISSUE TITLE
Confusing environment variable configuration

### ISSUE THREAD

**Issue by adrian-amaglio** [roundcube/roundcubemail-docker#87]
Hello,
I just tried to raise the `Maximum allowed file size` for attachments in Rondcube.

First, I saw this warning in the logs :
```
WARNING: /var/www/html/config/config.inc.php already exists.
ROUNDCUBEMAIL_* environment variables have been ignored.
```
I thought that the `ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE` would be ignored. I had to read the `docker-entrypoint.sh` script to see that it is used!

Maybe the warning message could be more specific about this ?

Thank you for all your work !

**Comment by thomascube** [comment]
We want to get rid of that warning entirely. See #112.

**Comment by thomascube** [comment]
Fixed in *-latest builds
