### ISSUE TITLE
404 Not Found Error on installer page

### ISSUE THREAD

**Issue by bmccorm2** [roundcube/roundcubemail-docker#91]
Hi all -

I am trying to configure roundcube via docker and I am getting a permission denied error on the installer page (http://localhost/installer). The main login page comes up just fine so i am pretty sure there is nothing wrong with my webserver. I have also configured the DB and user for roundcube and passed them in via the environment variables. In addition i set up server settings through the variables. When the container for both the db (mysql) and roundcube come up, there are no errors listed.

I'm having trouble finding any error messages or logs that will point me in the right direction. Has anyone seen this before?

Thanks,
Bryan

**Comment by thomascube** [comment]
That’s because the Docker images do not contain the installer. They’re supposed to be configured through Docker env variables and custom config files as described in the README. This is not a bug but the way the Docker images work.

**Comment by bmccorm2** [comment]
Thanks didn't even think to check if it was working before the installer.  I had everything configured right and it comes right up.  Thanks!

**Comment by JokerQyou** [comment]
However I don't think the `db_prefix` settings will work without going through the installation process.
