### ISSUE TITLE
Version Tags Missing for 1.4.6 and 1.4.7

### ISSUE THREAD

**Issue by nick-oconnor** [roundcube/roundcubemail-docker#92]
DockerHub is missing tags for 1.4.6 and 1.4.7. Based on the last updated time for the 1.4.X tags, it appears that the builds are being published, just not tagged with the specific versions.

**Comment by thomascube** [comment]
Indeed, I forgot to push the recent tags. Sorry for this! The 1.4.6 version was never released as Docker image because the single change only affected the installer which is not part of the Docker distribution.

**Comment by nick-oconnor** [comment]
Thanks for pushing the tags! I wasn't sure if something was broken. It makes sense if it's a manual process.

**Comment by robin-thoni** [comment]
@thomascube Would it make sense to you to setup a CD process? Would some help be required/appreciated?

**Comment by thomascube** [comment]
@robin-thoni Any suggestions or contributions for a better automation would be much appreciated.
