### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by robin-thoni** [roundcube/roundcubemail-docker#93]
New issue to talk about automation, as started in #92.

I had a quick look, and using the `Builds` tab on Docker Hub sounds the easiest way to achieve automatic builds:

(Done with https://github.com/robin-thoni/roundcubemail-docker and https://hub.docker.com/r/robinthoni/roundcube)

![image](https://user-images.githubusercontent.com/9640353/87815119-55812300-c865-11ea-9e3b-e949da62a4f8.png)

![image](https://user-images.githubusercontent.com/9640353/87815086-4306e980-c865-11ea-9031-ef038da26757.png)

This is very straight forward: just a few clicks to set it up on Docker Hub (no action required on GitHub if you link your account with Docker Hub), then you just push, and Docker Hub will build for you.

Under the hood, Docker Hub will create a Webhook and add a public key to the repo in order to get push events and clone the project (not really sure why the key is required for a public repo though)

Does that help?

**Comment by thomascube** [comment]
This is what we already have set up. So committing to this repo or pushing tags (if not forgotten) automatically triggers builds on Docker Hub.

What's missing in terms of a full automation is the connection between publishing a new releases on the [roundcube/roundcubemail](https://github.com/roundcube/roundcubemail) repo and updates to this repo (-> which again trigger Docker builds).

So this is what's currently being done by hand whenever a new Roundcube release is published:

- switch to master branch and update the `ROUNDCUBEMAIL_VERSION` in each `Dockerfile` and commit/push
- depending on the version number, switch to 1.4.x or 1.3.x branch, update the `ROUNDCUBEMAIL_VERSION` in each `Dockerfile` and commit/push
- create tags for the new version from either branch and push

There are according hooks on Github to get notified when new releases are published. What's missing is a script running somewhere reachable by a webhook that executes the above steps and is privileged to push to this repo. Any ideas on this?

**Comment by thomascube** [comment]
Looking into [Github Actions](https://docs.github.com/en/actions) for this. From the introduction, this could help us adding the missing piece of automation for new Docker releases.

**Comment by robin-thoni** [comment]
Oh sorry, I forgot about this... Yeah, Github Actions and Docker Hub builds were the pieces I looked at. For a simple workflow, Docker Hub builds are much easier. However, in that case, adding an Action on the main repo to trigger a Docker Hub build sounds the way to go:
![image](https://user-images.githubusercontent.com/9640353/89868760-3eef9280-dbab-11ea-90ac-23bc724e0c4e.png)

Basically, you set a name in the `Build triggers` section on the Docker Hub build tab, and you send a post request on the provided URL when the main repo gets updated. Does it make sense?

**Comment by pabzm** [comment]
Closing this since automation works these days
