### ISSUE TITLE
config file doesnt bootstrap DB

### ISSUE THREAD

**Issue by Goldenstarc** [roundcube/roundcubemail-docker#94]
Hi,
when you want to use image for first time with prepeared defaults.inc.php file which have DB connection strinng inside it,
it does not create DB schema after running.
so you first have to use run image with ENV variable (ROUNDCUBEMAIL_DB_HOST & ...) and next when DB is created, you can use costumized config file.

**Comment by thomascube** [comment]
The Roundcube Docker images are intended to be primarily configured with the provided ENV variables. The custom config files should only contain settings that cannot be defined with an ENV var. Also, the `defaults.inc.php` file shall never be changed. As the name suggests, it holds default values which are overwritten by the local config files derived from ENV vars and [custom config files](https://github.com/roundcube/roundcubemail-docker#advanced-configuration).

**Comment by Goldenstarc** [comment]
> The Roundcube Docker images are intended to be primarily configured with the provided ENV variables. The custom config files should only contain settings that cannot be defined with an ENV var. Also, the `defaults.inc.php` file shall never be changed. As the name suggests, it holds default values which are overwritten by the local config files derived from ENV vars and [custom config files](https://github.com/roundcube/roundcubemail-docker#advanced-configuration).

this is how my docker run command:

docker run \
    --name roundcubemail \
    -p 8084:80 \
    -v $(pwd)/config/:/var/roundcube/config/ \
    --restart=always \
    -d roundcube/roundcubemail
