### ISSUE TITLE
I can't use smtp for user that are not in docker mail

### ISSUE THREAD

**Issue by hubigin** [roundcube/roundcubemail-docker#95]
Hello,
I use docker mail and docker roudncube but recently i c'ant send mail for user that are not in docker mail 
I have two error :

- When the user are in other server but in same domaine:
Recipient address rejected: User unknown in virtual mailbox table

- When the user are a other domaine :
Recipient address rejected: Relay access denied

thanks

**Comment by thomascube** [comment]
These are errors returned by the SMTP server which is not part of Roundcube and neither of the Roundcube Docker image. You need to investigate the container/service your Roundcube container connects to via SMTP (see `-e ROUNDCUBEMAIL_SMTP_SERVER`).

**Comment by hubigin** [comment]
I don't know because with my client mail thunderbird there are no problem. So while there no probleme with thunderbird ? I have two docker :  tvial/docker-mailserver ,roundcubemail-docker.
