### ISSUE TITLE
Automatic upgrade for fpm-alpine?

### ISSUE THREAD

**Issue by ckristo** [roundcube/roundcubemail-docker#96]
Hi,

I'm running the fpm-alpine Docker image served by a separate Nginx instance. The roundcube source is stored on a named volume accessed by the Nginx instance to serve static files.

When doing an upgrade, I currently backup my config.inc.php, remove the named volume, pull the new image, recreate the container and restore the config file. It would be great if the upgrade is done automatically when the image is recreated - as Nextcloud does e.g.: it detects that the volume contains the source of an old version and updates the source files automatically (cf. https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L87). Do you think we could implement something similar for the roundcube fpm-alpine variant?

BR,
Chris

**Comment by thomascube** [comment]
Similar to #58. It seems like we need a upgrade path as outlined in the last comment of issue #58.

**Comment by thomascube** [comment]
Fixed with commit 58f49d1.

Each container start will perform an update if `/var/www/html` is mounted to a volume. Please test with latest builds and report if you find issues with the new behavior.
