### ISSUE TITLE
dovecot ident

### ISSUE THREAD

**Issue by chongma** [roundcube/roundcubemail-docker#98]
Hi I am planning to migrate to docker container from manual installation.

The manual installation has the dovecot_ident plugin installed to ensure that the user's ip address is logged in the dovecot logs.  This seems like a fairly important feature to me as otherwise you have no idea where your users are connecting from.

Is there a chance this plugin could be included as default?   otherwise could you let me know the best way to include in my image?

I was also using the markasjunk2 plugin instead of markasjunk as it had some better features.  but do you recommend moving back to markasjunk which is included by default?

**Comment by thomascube** [comment]
There's a related issue #97 which asks for simplified integration of 3rd party plugins. For the time being, creating a [Custom Docker Image](https://github.com/roundcube/roundcubemail-docker#building-a-docker-image) might be a way to go.

**Comment by chongma** [comment]
When creating a custom docker image it says `[InvalidArgumentException]                                                                                                                                                                                                 
  Could not find a matching version of package corbosman/dovecot_ident. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).`

should roundcube log the user's ip address in dovecot by default without need for an extra plugin?  (maybe it does but i am not aware)

**Comment by thomascube** [comment]
@chongma It seems like that plugin is not registered to the Roundcube plugins repository or packagist.org. You need to pull it from [Github](https://github.com/corbosman/dovecot_ident) or a [fork of it](https://github.com/ANB777/dovecot_ident) and copy it into your image via your Dockerfile.

**Comment by chongma** [comment]
i have done 
```dockerfile
FROM roundcube/roundcubemail:latest
COPY ./dovecot_ident-master/ /var/www/html/plugins/dovecot_ident/
```
but the directory dovecot_ident is never created.  also the logs show
```
WARNING: /var/www/html/config/config.inc.php already exists.
ROUNDCUBEMAIL_* environment variables have been ignored.
Generating locales (this might take a while)...
  en_US.UTF-8... done
```
1. the config seems to be created correctly so this message seems strange
2. i need the locale en_GB.  i tried installing it manually but it is overridden by en_US

**Comment by chongma** [comment]
is there some restriction on copying a directory?  do i need to change user?

**Comment by thomascube** [comment]
If you read the Dockerfile of this project you'll find out that the target directory should be `/usr/src/roundcubemail` and not `/var/www/html`.

See https://git.rthoni.com/robin.thoni/docker-roundcube-server for an example of a customize Roundcube Docker image.
