### ISSUE TITLE
Is there any working example on how to run with docker-compose?

### ISSUE THREAD

**Issue by hth2** [roundcube/roundcubemail-docker#99]
I am new to roundcube, and apologize if this question is trivial: 

Is there any working example on how to run roundcube with docker-compose?

**Comment by robin-thoni** [comment]
I do have one here, if that helps you: https://git.rthoni.com/robin.thoni/docker-roundcube-server

**Comment by hth2** [comment]
thank you for the link, very much appreciated.

**Comment by thomascube** [comment]
We have just added a few examples [here](/roundcube/roundcubemail-docker/tree/master/examples).
